### ISSUE TITLE
is it possible to run test cases for changed packages?

### ISSUE THREAD

**Issue by SAGARSURI** [invertase/melos#100]
I have my flutter project in git. I want to run only those module's tests which are changed or not pushed to git. I wanna do that in a pre-push git hook. coz running all tests every push can be really slow. Is it possible?

**Comment by Salakar** [comment]
You can filter by packages that have changed since a git commit or ref (e.g. branch name) using the `--since=main` package filter, e.g.;

```
melos exec --since=main -- "echo 'Hello from the MELOS_PACKAGE_NAME package!'"
```

It can't filter specific tests inside an individual package though unfortunately, melos has no concept of that unfortunately.
