### ISSUE TITLE
Question: Pre-defined configurations in IntelIj are removed when running melos bootstrap

### ISSUE THREAD

**Issue by SAGARSURI** [invertase/melos#124]
Hey @Salakar 
I have pre-defined configurations in my IntelIj IDE like running a different flavor of my app(dev, staging, prod). But when I run the `melos bs` command. Those configurations are removed.
<img width="466" alt="Screenshot 2021-06-08 at 1 49 13 PM" src="https://user-images.githubusercontent.com/14856659/121149478-52699980-c860-11eb-8443-743b57b96ac5.png">

I only see these are added back but I lose my own configurations.

**Comment by Salakar** [comment]
Interesting, am taking a look - it shouldn't be doing that

**Comment by Salakar** [comment]
Looking at the cleanup logic it should only be removing files that match `melos_*.xml` - how are you naming your own configurations?

**Comment by Salakar** [comment]
Have tested with a custom config and it remains after `melos clean` and `melos bs`:

![image](https://user-images.githubusercontent.com/5347038/121179743-f7cc3f80-c857-11eb-9ea1-d22343f020c7.png)

**Comment by SAGARSURI** [comment]
I guess I understand the problem. It's happening because I don't store it as a file. I don't have the option "Store as project file" selected.

**Comment by Salakar** [comment]
> Also, I see `melos bs` disable Dart for some of the packages. I have to manually enable it through the `Preferences` option.

Are you able to diff a `melos_*.iml` file before and after you manually enable Dart in preferences - something might be missing from the [templates](https://github.com/invertase/melos/tree/master/packages/melos/templates/intellij/modules)

**Comment by Salakar** [comment]
I just tried diffing myself by toggling it off and on - it doesn't seem like IntelliJ sets anything in the `.idea` folder or the *.iml files for this so I not sure what Melos could do since it looks like IntelliJ is setting this value somewhere else internally perhaps.

**Comment by SAGARSURI** [comment]
> > Also, I see `melos bs` disable Dart for some of the packages. I have to manually enable it through the `Preferences` option.
> 
> 
> 
> Are you able to diff a `melos_*.iml` file before and after you manually enable Dart in preferences - something might be missing from the [templates](https://github.com/invertase/melos/tree/master/packages/melos/templates/intellij/modules) 

Yeah sure. I will try that and update.

**Comment by SAGARSURI** [comment]
Okay in that I will check with the IntelIj flutter plugin team on this. Thanks for giving your time and looking into it. Much appreciated.

**Comment by SAGARSURI** [comment]
Here is the diff before and after enabling Dart for a particular package after running `melos bs`
<img width="1601" alt="Screenshot 2021-06-08 at 8 44 16 PM" src="https://user-images.githubusercontent.com/14856659/121211828-6d58ff80-c89a-11eb-9b09-6dcf9de053db.png">

**Comment by Salakar** [comment]
Ah I see it's the root module causing an issue;

Can you add those 2 lines to your local/development copy of Melos - in packages/melos/templates/intellij/modules/workspace_root_module.imp.tmpl` - and see if that solves the problem when you run bootstrap? If it does would you mind sending a PR?

**Comment by SAGARSURI** [comment]
Yeah sure. Let me try it out.

**Comment by SAGARSURI** [comment]
I have created a PR #127

**Comment by SAGARSURI** [comment]
Thank you so much for helping me out to raise a PR. I never had such an interactive discussion with anyone in the open-source community.
