### ISSUE TITLE
`.dart_tool/melos_tools/` is not replaced in generated files on unix

### ISSUE THREAD

**Issue by blaugold** [invertase/melos#144]
The files, which are generated during bootstrap and contain absolute paths, still include `.dart_tool/melos_tools/` in those paths after bootstrap. This is only an issue on operating systems where the `\` is not a path separator. The cause is that the `RegExp` which matches `.dart_tool/melos_tools/` is not fully platform specific. It expects the path separator after `.dart_tools` to always be `\`.

I have opened a PR (#143) to fix this.

**Comment by Salakar** [comment]
Thanks for the PR, there a ton of conflicts now that #140 has landed sorry - I have pushed a fix though for this - will publish `0.5.0-dev.1` shortly

**Comment by Salakar** [comment]
`0.5.0-dev.2` is now available for testing

**Comment by blaugold** [comment]
I'm just glad it's fixed. Thanks!
