### ISSUE TITLE
Request: allow passing cli args to melos run

### ISSUE THREAD

**Issue by lesnitsky** [invertase/melos#153]
Example usage:

```sh
melos run test:mobile_e2e -- -d emulator-5554
                          ^^^^^^^^^^^^^^^^^^^
```

**Comment by fstof** [comment]
This would indeed be handy...

passing in args to a melos script could be made accessible similar to bash script arguments $0 $1 etc...

```yaml
  some_script:
    run: |
      echo $0 && 
      echo $1 && 
      echo $2
```

`melos run some_script hello world`

would produce the output
```
some_script
hello
world
```

**Comment by Salakar** [comment]
I have a draft PR locally that supports this, in the format @lesnitsky mentioned, 

```bash
melos run test:mobile_e2e -- -d emulator-5554
```

note the args come after the ` -- `

Just need to test a few more things out before I can ship it

**Comment by jeroen-meijer** [comment]
Awesome stuff, I agree this would be extremely useful for a couple workflows I know of for myself and some companies! 😄 

Any updates on your progress, @Salakar? 👀

**Comment by jeroen-meijer** [comment]
Awesome work, thanks @Salakar! 🎉

**Comment by Noteofman** [comment]
Could I get an example of these being passed in and used, as its not mentioned anywhere in the docs.

**Comment by Salakar** [comment]
> Could I get an example of these being passed in and used, as its not mentioned anywhere in the docs.

There's an example above, https://github.com/invertase/melos/issues/153#issuecomment-1010744759

**Comment by Noteofman** [comment]
> > Could I get an example of these being passed in and used, as its not mentioned anywhere in the docs.
> 
> There's an example above, https://github.com/invertase/melos/issues/153#issuecomment-1010744759

Indeed, however I wasn't able to access these arguments in the running script. Not sure if I'm missing something here.
