### ISSUE TITLE
The plugin `X` doesn't have a main class

### ISSUE THREAD

**Issue by btrautmann** [invertase/melos#154]
Hi there! Our team has been doing a spike on what it would look like to migrate our project to using `melos`. We've started by moving all our packages into `packages` which we specify within the `melos.yaml`. So far, everything has worked. When we finally moved the last package which is our actual `app` package and `main` executable, we started getting errors along the lines of:

```
The plugin `example` doesn't have a main class defined in /path/to/example/ExamplePlugin.java or /path/to/example/ExamplePlugin.kt. This is likely to due to an incorrect `androidPackage: com.example` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 

• app
    └> ./packages/app
    └> Failed to run "flutter pub get" in this package.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Bootstrap failed: "flutter pub get" failed in one of your workspace packages.
```

It's worth noting that `flutter pub get` in the actual package that's being called out here succeeds.

While trying to debug this, I removed the plugin in question as a dependency from all packages that were declaring it as one, and the error moved on to _another_ local plugin, so I'm thinking it's not specific to the plugin that originally had the error.

We're currently using Flutter `2.2.2` on the stable channel and Dart `2.13.3`. 

Thank you in advance for any help!

**Comment by Salakar** [comment]
Hey are you able to provide an example of what the pubspec looks like for your app package?

**Comment by btrautmann** [comment]
> Hey are you able to provide an example of what the pubspec looks like for your app package?

I created a gist [here](https://gist.github.com/btrautmann/770137f77b1f8a2b6598e31ff81e6f51). I redacted any specific names, but left the structure un-touched!

**Comment by btrautmann** [comment]
@Salakar any thoughts or avenues you'd recommend taking to figure this out?

**Comment by btrautmann** [comment]
Update: I did more digging into `melos` source code last night, and learned about the package mirroring that happens on a `melos bootstrap`. In learning this, it became clear that `flutter pub get` is looking for the main class for each plugin that supports Android and it's not finding it because those files are not copied over to the mirror. I was able to get the actual bootstrap to work by commenting out the plugin information in the `pubspec.yaml` but I don't think this is a reasonable path forward. Instead, it may be necessary to copy over the main class so that `flutter pub get` can find it and be appeased.

If this is true, I have a few questions:

1. How has this not yet been discovered? Is it possible that we're declaring/defining our plugin configuration oddly by having the following in our `pubspec.yaml`?
```
plugin:
  platforms:
    android:
      package: com.example.my_plugin
      pluginClass: MyPlugin
    ios:
      pluginClass: MyPlugin
```
I'll do some digging into other projects using melos to see if there's something we're doing wrong.

2. If we're NOT doing something wrong and there's some _other_ reason this hasn't been discovered, I'd love to know if copying the main file is the way to go. Unfortunately, I don't know that the pubspec library provides enough information on this to be used by `melos`, so it may be a 2 PR solution

Curious to hear y'alls thoughts.

**Comment by samandmoore** [comment]
I'm created a repo with a reproduction of this issue. 

The recipe that results in this error is having a `module` (flutter add-to-app module) that depends on a `plugin`. 

you can check it out here: https://github.com/samandmoore/melos-dd-to-app-issue

if you remove these lines then bootstrap works https://github.com/samandmoore/melos-dd-to-app-issue/blob/c5f527bed6a8ada89dc7b616996d74de7608fc58/packages/zee_module/pubspec.yaml#L31-L32 as soon as you add them back in, you get a confusing error:

```
$ melos bootstrap
melos bootstrap
   └> /Users/sammoore/src/melos-add-to-app-issue

Running "flutter pub get" in workspace packages...
  ✓ zeeplugin_example
     └> ./packages/zeeplugin/example

------------------------------------------------------------------------------------------------------------------------------------------------------------------
Running "flutter pub get" in zee_module...
Running "flutter pub get" in zee_module...                         590ms
Warning: You are using these overridden dependencies:
! zeeplugin 0.0.1 from path ../zeeplugin
The plugin `zeeplugin` doesn't have a main class defined in /Users/sammoore/src/melos-add-to-app-issue/.dart_tool/melos_tool/packages/zeeplugin/android/src/main/java/com/example/zeeplugin/ZeepluginPlugin.java or /Users/sammoore/src/melos-add-to-app-issue/.dart_tool/melos_tool/packages/zeeplugin/android/src/main/kotlin/com/example/zeeplugin/ZeepluginPlugin.kt. This is likely to due to an incorrect `androidPackage: com.example.zeeplugin` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.
• zee_module
    └> ./packages/zee_module
    └> Failed to run "flutter pub get" in this package.
------------------------------------------------------------------------------------------------------------------------------------------------------------------

Bootstrap failed: "flutter pub get" failed in one of your workspace packages.
```

All the files are where they're supposed to be and the module is using the proper pubspec.yaml syntax for add-to-app modules and the plugin is using the proper pubspec.yaml syntax for a plugin. It's like the pub get call is getting confused and printing a weird error message.

**Comment by btrautmann** [comment]
Closing this now because https://github.com/invertase/melos/pull/162 merged and is available in https://github.com/invertase/melos/releases/tag/melos-v1.0.0-dev.3.
