### ISSUE TITLE
`melos init` results in `Could not find a command named "init"`

### ISSUE THREAD

**Issue by Sunbreak** [invertase/melos#158]
According to https://github.com/invertase/melos/blob/master/docs/getting-started.mdx

> New project? Use `melos init` to initialize the file and an empty `packages` directory.

## Actual results

```sh
$ melos init
Unhandled exception:
Could not find a command named "init".
...
```

## Expected results

Update the doc to `melos bootstrap`

**Comment by spydon** [comment]
It seems like the docs have been updated to `melos bootstrap` and this can be closed?
