### ISSUE TITLE
Melos exec doesn't terminate for build_runner command

### ISSUE THREAD

**Issue by prolificcoder** [invertase/melos#173]
Just started giving this a try. In one of the packages I need to run this build_runner command

`flutter packages pub run build_runner build`

when i invoke it from `melos exec` it just hangs even though it succeeded

![image](https://user-images.githubusercontent.com/149176/132766156-69482d4f-ea6e-4de9-b127-66599e0338cd.png)

But if I run `flutter pub get` it works fine
![image](https://user-images.githubusercontent.com/149176/132766221-087e9440-f548-43e3-b73c-e4f87c4bea58.png)

**Comment by danilofuchs** [comment]
Please use one of the dev versions:
```
dart pub global activate melos 1.0.0-dev.3
```

**Comment by prolificcoder** [comment]
@danilofuchs 
I am getting still the same issue
![image](https://user-images.githubusercontent.com/149176/132917685-86ec55ba-511a-4fc7-aa4c-b0ae79025870.png)

**Comment by Salakar** [comment]
This is fixed in the v1.0.0 releases - please try v1.0.0-dev.3 for example, thanks

**Comment by easazade** [comment]
I activated 1.0.0-dev.10 and i still have the same issue

**Comment by easazade** [comment]
i tried 1.0.0-dev.10 and at first it didn't work. but then i first deactivated it. and made sure the melos command was not available and the reactivated it. this time it worked.
