### ISSUE TITLE
Package Filtering in melos.yaml different results

### ISSUE THREAD

**Issue by ABausG** [invertase/melos#181]
I want to constrain a melos command based on two factors:

1. Only run command in `example` directory
2. Only run if there is a `android` directory

If I define these constrains in the execution like this:

```
build:example_android_pub:
    run: |
      melos exec -c 6 --dir-exists="android" --scope="example" --fail-fast -- \
        "flutter build apk"
    description: Build a specific example app for Android.
```

I get the following (expected) output

```
$ melos run build:android
melos run build:android
   └> melos run build:example_android_pub --no-select && melos bootstrap
       └> RUNNING

melos run build:example_android_pub
   └> melos exec -c 6 --dir-exists="android" --scope="example" --fail-fast -- \  "flutter build apk"
       └> RUNNING

$ melos exec
   └> flutter build apk
       └> RUNNING (in 3 packages)
```

Notably it is running in **3 packages**.

However if I define the constrains like with `select-package` in the `melos.yaml` file

```
build:example_android_pub:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter build apk"
    description: Build a specific example app for Android.
    select-package:
      dir-exists:
        - "android"
      scope:
        - "example"
```

I get the output:

```
$ melos run build:android
melos run build:android
   └> melos run build:example_android_pub --no-select && melos bootstrap
       └> RUNNING



melos run build:example_android_pub
   └> melos exec -c 6 --fail-fast -- \  "flutter build apk"
       └> RUNNING

$ melos exec
   └> flutter build apk
       └> RUNNING (in 4 packages)
```

This now also builds a **4th package** that does not have an `android` directory and thus is failing.

By changing it in the command it is working however I personally prefer the readability of the yaml declaration so it would be nice if that would work

**Comment by blaugold** [comment]
It seems like this is working now. If this issue is not resolved for you, please comment and I can reopen it.
