### ISSUE TITLE
Question: melos bs couldn't work on test.

### ISSUE THREAD

**Issue by huang12zheng** [invertase/melos#207]
* dart test                  
```      
Resolving dependencies... (19.4s)
Because romantic_common depends on masonx ^0.0.9 which doesn't match any versions, version solving failed.
```
```yaml
dev_dependencies:
  masonx: ^0.0.9 
```

* from doc,
```
packages field will be locally linked whilst other dependencies will be automatically installed 
```

in fact, melos bs couldn't work on test.

- [ ] Is this as expected?
- [ ] Is there any other way to solve the problem other than dependency_overrides
---
to solve it,
I add some thing in pubspec.yaml
```yaml
dependency_overrides:
  masonx:
    path: ../masonx
```

**Comment by Salakar** [comment]
Related to https://github.com/invertase/melos/issues/117 so going to close; TLDR flutter/dart run/test automatically run pub install - which overwrites melos and breaks package interlinking (there's is a `--no-pub` flag though on some of those commands so try that).

**Comment by huang12zheng** [comment]
also ref to https://github.com/dart-lang/pub/pull/3199
