### ISSUE TITLE
Melos no longer working after Flutter 2.8.0

### ISSUE THREAD

**Issue by ShakyaCsun** [invertase/melos#209]
Running `flutter pub global activate melos` generates a warning:
Warning: Executable "melos" runs "bin\melos.dart", which was not found in melos.
![image](https://user-images.githubusercontent.com/38353746/145527241-7ebb560f-f668-4808-bc53-d42ac5fc46a0.png)

Running `melos` commands simply outputs:
> No active package melos.

I have also tried the latest dev version of melos ^1.0.0-dev.14, the issue still persists.

**Comment by xal** [comment]
@ShakyaCsun I have similar issues with older flutter versions too, but I think it is related to FVM use in my project. You can replace `melos` run `flutter pub global run melos`  and it should work even if executables setup fails

**Comment by ShakyaCsun** [comment]
I am not using FVM, but running `flutter pub global run melos` solves the issue and everything runs normally with just `melos` command afterwards.

Maybe this could be documented somewhere as a workaround if the issue is reproducible by other people on Flutter 2.8.0. On my machine, I found I always get the `No active package melos.` after I deactivate and re-activate melos and it can be fixed by running `flutter pub global run melos` once.

**Comment by kolotum** [comment]
We had a similiar error since Flutter 2.8 on our CI Server. It worked after we switched from `flutter pub global activate melos` to `dart pub global activate melos`

**Comment by Salakar** [comment]
Closing as this wasn't an issue with Melos itself and just need to re-activate it globally through pub

**Comment by lukepighetti** [comment]
Just ran into this, cause appears to be installing with `flutter pub global activate melos` instead of `dart pub global activate melos`.

Solution was to run `flutter pub global run melos --version` in a project directly with a valid `melos.yaml` file, then `melos --version` would work.

**Comment by hpelitebook745G2** [comment]
`flutter pub global activate melos` worked for me
