### ISSUE TITLE
Support fvm

### ISSUE THREAD

**Issue by ened** [invertase/melos#21]
Could this project support [fvm](https://pub.dev/packages/fvm)?

At the moment, given a melos.yaml like this:

```
name: connect

packages:
  - packages/**

scripts:
  analyze: melos exec -- pub global run tuneup check
  postbootstrap: tuneup --version || pub global activate tuneup
  postclean: melos exec -- rm -rf ./build ./android/.gradle ./ios/.symlinks ./ios/Pods ./android/.idea ./.idea
```

executing `fvm flutter pub global run melos bootstrap` stops with:

```
$ fvm flutter pub global run melos bootstrap
FVM: Running version 1.20.4
$ melos bootstrap
   └> /Users/ened/git/com.company.app

Bootstrapping project...
/bin/sh: line 1: flutter: command not found
Bootstrap failed, reason: pub get failed, see logs above.
pub finished with exit code 1
```

**Comment by Salakar** [comment]
This is certainly possible, we can check if fvm exists and fall back to that instead of flutter

**Comment by ened** [comment]
> I guess the only consideration is what should happen if both flutter and fvm are detected

I think you can safely call `fvm` anyway, if it's in path.
In a project that without fvm config, fvm will simply forward to `flutter` binary that's in path (or fail):

```
fvm flutter --version             
FVM: Running using Flutter version configured in path.
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (6 weeks ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

@leoafarias anything to add?

**Comment by leoafarias** [comment]
In order to keep things cleaner o Melos end... fvm set the env var for the process when executing 'fvm flutter'

Would that make it compatible?

**Comment by leoafarias** [comment]
@ened let me know if this works for you
`pub global activate fvm 1.3.6-dev.1`

**Comment by orestesgaolin** [comment]
Another idea is to allow to pass arbitrary path to Flutter installation. This way it wouldn't be tied to fvm only.

**Comment by quirijnAtPropertyMe** [comment]
> Another idea is to allow to pass arbitrary path to Flutter installation. This way it wouldn't be tied to fvm only.
Maybe a local Melos config file that's not in VCS?

**Comment by QuirijnGB** [comment]
> Another idea is to allow to pass arbitrary path to Flutter installation. This way it wouldn't be tied to fvm only.

Maybe a local Melos config files thats not checked in to VCS?

**Comment by Salakar** [comment]
Open to suggestions/proposals/PRs 👍

**Comment by vasilich6107** [comment]
on fvm 1.3.7 - `fvm flutter pub global run melos bootstrap` works good

**Comment by Salakar** [comment]
Thanks for confirming working, I will close this issue now.

**Comment by vasilich6107** [comment]
One note. `melos publish` gives

```
melos publish --dry-runook-Pro reactive_forms_widgets % fvm flutter pub global run melos publish
   └> /Users/vasilich/IdeaProjects/reactive_forms_widgets

Reading pub registry for package information...

The following packages will be validated only (dry run):

Package Name                  Registry    Local    
reactive_date_range_picker    none        0.0.1    
reactive_date_time_picker     0.0.1       0.0.2    
Unhandled exception:
StdinException: Error getting terminal echo mode, OS Error: Inappropriate ioctl for device, errno = 25
#0      Stdin.echoMode (dart:io-patch/stdio_patch.dart:71:7)
#1      get (package:prompts/prompts.dart:60:27)
#2      getBool (package:prompts/prompts.dart:175:16)
#3      promptBool (package:melos/src/common/utils.dart:78:10)
#4      PublishCommand.run (package:melos/src/command/publish.dart:130:28)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#6      MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:202:5)
<asynchronous suspension>
pub finished with exit code 255

```
