### ISSUE TITLE
Mention VS Code extension in docs

### ISSUE THREAD

**Issue by blaugold** [invertase/melos#212]
I'm not quite sure what the right place in the docs would be to mention the [VS Code extension](https://github.com/blaugold/melos-code).

I've seen that #126 adds a page for IDE integration, so if that's the designated area, this can wait until that PR is merged.

**Comment by Salakar** [comment]
I'll try get #126 merged today and then it can be sent up to there

**Comment by Salakar** [comment]
#126 is merged - I've left the IDE page blank - so it's all your's if you'd like to add a VS Code section with the extension etc 🎉

**Comment by blaugold** [comment]
Thanks! I'll do that.

**Comment by Salakar** [comment]
https://docs.page/preview docs.page supports local previewing now (with no additional tools required) - if you fancy trying that out too :D
