### ISSUE TITLE
melos bootstrap with multiple "example" packages broken

### ISSUE THREAD

**Issue by ABausG** [invertase/melos#214]
After upgrading from 0.4.11+2 to 1.0.0 I can't run `melos boostrap` anymore.

My project is structured like this:

```
| melos.yaml
| packages/
     | package_1/
          | lib/
          | example/
     | package_2/
          | lib
          | example/
     | package_3/
          | lib
          | example/
     | package_4/
          | lib
          | example/
     | package_5/
          | lib
```

Up to Version 0.4.11+2 I had no problems running `melos bootstrap` however after upgrading to 1.0.0 `melos bootstrap` fails with the following message:

```
melos.yaml: Multiple packages with the name `example` found in the workspace, which is unsupported.
To fix this problem, consider renaming your packages to have a unique name.

The packages that caused the problem are:
- example at packages/package_1/example
- example at packages/package_2/example
```

So weirdly it only complains about 2 of 4 packages that have an example project in them
---

I define which packages to use in `melos.yaml` like this:

```
packages:
  - packages/**
```

**Comment by Salakar** [comment]
Hey 👋 

As the error message states, multiple packages in the workspace with the same name are unsupported (since filters etc won't work properly since they are based on package name)

It's recommended that examples be named unique, e.g. `package_1_example`, `package_2_example` and so on.

It will only complain about the first occurrence it comes across and won't complain about all of them

**Comment by ABausG** [comment]
I would like to keep the name as example as the packages are published to pub.dev

As I (at least not right now) need to run melos commands for these examples I guess I could get away with them being ignored. However `melos boostrap` still complains even after adding:

```
ignore:
  - "packages/**/example"
```

to the melos.yaml file (same level as packages)

**Comment by blaugold** [comment]
> I would like to keep the name as example as the packages are published to pub.dev

You can leave the name of the directory `example` and just change the name of the example package in `pubspec.yaml`, if I understand your concern correctly.

**Comment by ABausG** [comment]
Ah yeah! 🤦‍♂️ Thanks :) That solves the issue instantly!

**Comment by cedvdb** [comment]
Note that the solution provided here does not work at this time as the package name must be the same as the folder or else 

![image](https://user-images.githubusercontent.com/22280985/200186754-acdc9ebb-5535-4b4b-baab-20df3d5feec6.png)
