### ISSUE TITLE
Bootstraping packages from other directory other than packages seems to not work

### ISSUE THREAD

**Issue by richard457** [invertase/melos#215]
I have this
```
packages:
  - packages/**
  - open/**
  - "*"
  ```
But when I run melos bootstrap only packages from packages folder are bootstrapped.

**Comment by richard457** [comment]
Seems like local melos.yml file is not recognized.

**Comment by Salakar** [comment]
File should be called `melos.yaml` note `yaml` instead of `yml`

**Comment by richard457** [comment]
Thanks
