### ISSUE TITLE
Having issue running "melos bs"

### ISSUE THREAD

**Issue by sanihaq** [invertase/melos#216]
Unhandled exception:
Bad state: Stream has already been listened to.
#0      _StreamController._subscribe (dart:async/stream_controller.dart:635:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
#3      _Socket.listen (dart:io-patch/socket_patch.dart:2162:31)
#4      _StdStream.listen (dart:io/stdio.dart:22:20)
#5      Stream.reduce (dart:async/stream.dart:821:14)
#6      _BootstrapMixin._logPubGetFailed (package:melos/src/commands/bootstrap.dart:79:12)
#7      _BootstrapMixin.bootstrap.<anonymous closure> (package:melos/src/commands/bootstrap.dart:40:19)
<asynchronous suspension>
#8      _Melos._runLifecycle (package:melos/src/commands/runner.dart:119:7)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:82:5)
<asynchronous suspension>
#11     main (file:///C:/Users/Sani/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/melos-1.0.0/bin/melos.dart:10:5)
<asynchronous suspension>

**Comment by smiLLe** [comment]
Happens to me as well. @sanihaq  Did you solve the issue?

**Comment by sanihaq** [comment]
@smiLLe  not really, using path like this for now
```
common_utils:
   	path: ../common_utils
```
waiting for a fix...

**Comment by blaugold** [comment]
This hack prevents `_logPubGetFailed` from reading `stdout` of the process in case of an error:

https://github.com/invertase/melos/blob/d9151422b053d7ca157b220fda84a3e0ecabf2a4/packages/melos/lib/src/commands/bootstrap.dart#L144-L149

A fix would need to ensure that `process.stdout` is always listened to exactly once.

**Comment by nik-v-hax** [comment]
any update or temporary workaround on this?

**Comment by smiLLe** [comment]
I had to downgrade to `0.4.11+2`
