### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by richard457** [invertase/melos#217]
Bad state: Stream has already been listened to.
#0      _StreamController._subscribe (dart:async/stream_controller.dart:635:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
#3      _Socket.listen (dart:io-patch/socket_patch.dart:2162:31)
#4      _StdStream.listen (dart:io/stdio.dart:22:20)
#5      Stream.reduce (dart:async/stream.dart:821:14)
#6      _BootstrapMixin._logPubGetFailed (package:melos/src/commands/bootstrap.dart:79:12)
#7      _BootstrapMixin.bootstrap.<anonymous closure> (package:melos/src/commands/bootstrap.dart:40:19)
<asynchronous suspension>
#8      _Melos._runLifecycle (package:melos/src/commands/runner.dart:119:7)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:82:5)
<asynchronous suspension>
#11     main (file:///C:/Users/Sone/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/melos-1.0.0/bin/melos.dart:10:5)
<asynchronous suspension>

**Comment by sanihaq** [comment]
Duplicate of #216

**Comment by Salakar** [comment]
Closing in favour of #216
