### ISSUE TITLE
Support app + packages repository style

### ISSUE THREAD

**Issue by ened** [invertase/melos#22]
Our main App has grown quite significantly and some of the core components have moved into the `packages` folder.

This leaves us with the main app in `/` and supporting packages in `/packages`.

When configuring `melos.yaml` like so:

```
name: connect

packages:
  - .
  - packages/**

scripts:
  analyze: melos exec -- pub global run tuneup check
```

Then only the `packages/*` folders are taken into consideration & evaluated.
If I run `pub global run tuneup check` in the root folder, it works as expected though.

Is it feasible to support this kind of directory layout?

**Comment by Salakar** [comment]
Hey, this is definitely possible, this repo itself is doing that, your config needs to look like this: https://github.com/invertase/melos/blob/master/melos.yaml#L2

**Comment by ened** [comment]
@Salakar thank you very much!
