### ISSUE TITLE
melos commands fail w/o melos.yaml

### ISSUE THREAD

**Issue by lesnitsky** [invertase/melos#23]
after executing any command I get this output:
```
Your current directory does not appear to be a valid workspace.
Does the "melos.yaml" file exist in the root?
```

Shouldn't init command create this file?

**Comment by Salakar** [comment]
The `init` command hasn't been implemented yet (PRs welcome!) - however having said that a `melos.yaml` file is only required if you need custom configuration and/or want to define scripts etc. 

The way it works without a melos.yaml file is that it assumes a directory structure where all your packages are in a `packages` directory in the root - what does your project file structure look like?

**Comment by lesnitsky** [comment]
oh, I didn't realize melos would work w/o melos.yaml. [This paragraph](https://github.com/invertase/melos#existing-projects) made me think so. + error message also suggested melos.yaml is mandatory (that was a new project w/o `packages/` folder yet)

**Comment by Ehesp** [comment]
Yeah was a recent addition that, docs need updating.

**Comment by Salakar** [comment]
I've updated the readme now - thanks :)

**Comment by lesnitsky** [comment]
kudos
