### ISSUE TITLE
Melos GitHub action

### ISSUE THREAD

**Issue by spydon** [invertase/melos#230]
It would be great to have a Melos GitHub action that provides an environment with melos pre-activated in, then other GitHub actions could easily depend on that to run melos actions in their CI/CD pipelines.

I guess you have seen this one for example which is widely used:
https://github.com/subosito/flutter-action

**Comment by spydon** [comment]
I could create this action, but it's probably best if it lives under your organization?
Otherwise we could create it under @bluefireteam too, if you don't want to maintain this. 
(It will be a very short file basically just activating melos)

It the action would be used it would eliminate the need for files like this one for example:
https://github.com/FirebaseExtended/flutterfire/blob/master/.github/workflows/scripts/install-tools.sh

**Comment by spydon** [comment]
Created the GitHub action here:
https://github.com/bluefireteam/melos-action
Tell me if you want to transfer it to your org.

**Comment by Salakar** [comment]
Thanks for creating the action! I'm obviously happy for you to keep it on your org, but if you think it won't get much maintenance in your org then I'd also be ok if you want to move the repo over to us - entirely up to you.

I noticed it's using a shell script, am I right in assuming it won't work on Windows yet?

**Comment by blaugold** [comment]
https://github.com/subosito/flutter-action only has a shell script but works on Windows. I think shell scripts are run with Git-Bash on GitHub actions by default.

**Comment by Salakar** [comment]
> [subosito/flutter-action](https://github.com/subosito/flutter-action) only has a shell script but works on Windows. I think shell scripts are run with Git-Bash on GitHub actions by default.

Good to know, thanks!

**Comment by spydon** [comment]
> Thanks for creating the action! I'm obviously happy for you to keep it on your org, but if you think it won't get much maintenance in your org or it'd be better on ours then I'd also be ok if you want to move the repo over to us - entirely up to you.

It will definitely get maintenance in our org since we'll use it on all our actions, just thought that maybe you'd want control over it. But we're fine hosting it under blue fire. :slightly_smiling_face: 

I guess we can close this one then and just link to https://github.com/bluefireteam/melos-action so that any folks searching for the action and end up on this ticket will find it.

**Comment by Salakar** [comment]
> I guess we can close this one then and just link to [bluefireteam/melos-action](https://github.com/bluefireteam/melos-action) so that any folks searching for the action and end up on this ticket will find it.

We could probably do with a mention in the docs about this also

**Comment by spydon** [comment]
The action is now published in [the marketplace](https://github.com/marketplace/actions/melos-action)
