### ISSUE TITLE
Focus mode

### ISSUE THREAD

**Issue by lukepighetti** [invertase/melos#236]
NOTE: this issue was first submitted here by mistake https://github.com/blaugold/melos-code/issues/29

-----

I noticed some monorepo tools allow for focus mode. 

Use case: I want to work on package B (which depends on package A), but I don't want to see, or have analyzer consider, packages C, D, E ... n

`melos focus <package_name>`

Would resolve it's dependencies and hide everything else.

This may inspire a change where an app needs to be defined in `melos.yaml` so that it too can be hidden from analyzer, otherwise it will just show a bunch of IDE errors whenever focus mode is enabled

**Comment by Almighty-Alpaca** [comment]
Something like this is already possible by using using package filters when bootstrapping the workspace, e.g. `melos bs --scope <package_name_or_glob> --include-dependencies`

**Comment by MINEGHOST007** [comment]
i would like to contribute in this please assign this to me

**Comment by spydon** [comment]
> i would like to contribute in this please assign this to me

Since this is already possible like described by Almighty-Alpaca, I'll close this.
