### ISSUE TITLE
Melos doesn't resolve dependency graph for local packages without additional command line flags

### ISSUE THREAD

**Issue by lukepighetti** [invertase/melos#238]
I posted this in the wrong repo by mistake, you can find that here: https://github.com/blaugold/melos-code/issues/30
------
When I open [this project](https://github.com/lukepighetti/spike_melos_task/tree/6a9aa4f9c1e2bde0c7ff757ed05315644b1bc774) and type `melos list` it only lists the `styles` package even though there is a `widgets` package that is consumed by the root app which depends on `styles`

```
% melos list --graph
{
  "styles": []
}
```

Apparently [this is due to Melos ignoring packages with publish_to: none](https://github.com/blaugold/melos-code/issues/30#issuecomment-1029377964) unless you pass the `--all` command line flag 

We cannot use paths for dependencies unless `publish_to: none` is set. 

<img width="1126" alt="Screen Shot 2022-02-03 at 5 24 43 PM" src="https://user-images.githubusercontent.com/666539/152439388-e23c3cdb-bbe9-4384-bfe8-ea0c64a36b84.png">

That means that Melos commands for listing packages does not work for local packages. It only works for packages that will be published.

There is an `--all` flag that will show those packages, but I believe these should be visible by default, since Melos does appear to be an excellent tool for internal use.

**Comment by Salakar** [comment]
I think we can make a `melos.yaml` configuration flag to include private packages by default - would this solve the problem for you? Otherwise I don't think we should just make this default behaviour since it'd be a breaking change 😅

**Comment by lukepighetti** [comment]
Perhaps some clarification on how Melos intends to connect multiple local packages into a dep graph to be consumed by an app. The fact that they are omitted makes me think that this is handled in a way that I am not utilizing. Or perhaps Melos is only intended for package authors like flutter fire? Some context would be helpful.

**Comment by Salakar** [comment]
@cabljac would you mind taking a look at this one - can sync on Slack when you're next free to look at it, thanks!
