### ISSUE TITLE
melos version (feature request)

### ISSUE THREAD

**Issue by lesnitsky** [invertase/melos#24]
As a maintainer of a monorepo I'd like to have a possibility to bump package versions with help of melos tool. Please let me know if that's in scope of the responsibilities of melos

**Comment by lesnitsky** [comment]
oops, that's already exist :D

**Comment by Salakar** [comment]
@lesnitsky forgot to reply to this but this has been now implemented :)

**Comment by lesnitsky** [comment]
awesome, thanks!
