### ISSUE TITLE
fix: melos bs will throw FileSystemException

### ISSUE THREAD

**Issue by smiLLe** [invertase/melos#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

1.2.1

### Description

Running `melos bs` will result in FileSystemException.
It happens right after `Linking workspace packages...`
OS: Windows

Nothing but VSCode is running. Command is executed in VSCode Terminal.
Happens also on older versions of melos.

```
Linking workspace packages...
Unhandled exception:
FileSystemException: Deletion failed, path = 'D:\_dev\[user]\endlich\.dart_tool\melos_tool' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#2      _CleanMixin.cleanWorkspace (package:melos/src/commands/clean.dart:30:42)
#3      _BootstrapMixin.bootstrap.<anonymous closure> (package:melos/src/commands/bootstrap.dart:54:9)
<asynchronous suspension>
#4      _Melos._runLifecycle (package:melos/src/commands/runner.dart:119:7)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:82:5)
<asynchronous suspension>
#7      main (file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/melos-1.2.1/bin/melos.dart:10:5)
<asynchronous suspension> 
```

### Steps to reproduce

Execute `melos bs` 

### Expected behavior

... No Exception

**Comment by smiLLe** [comment]
Okay it is VSCode related. Closing VSCode and just open a terminal will work as expected.

**Comment by smiLLe** [comment]
I deactivated all VSCode extensions except Dart and Flutter but the issue is still there.

**Comment by Tokenyet** [comment]
I can't give a good answer, but I have an experience of dart's `FileSystem`. If one of the path in the directory is too long, the deletion fail.
https://github.com/dart-lang/sdk/issues/27825

In windows, we should add `\\?\`  as I said in the issue.

**Comment by Salakar** [comment]
> I just add the code from metioned issue, the problem sloved. Not sure If I should make a PR from my repo

Please do make a PR, thanks!

Also is there any documentation anywhere on why `\\?\` makes it work? 😅

**Comment by Tokenyet** [comment]
> > I just add the code from metioned issue, the problem sloved. Not sure If I should make a PR from my repo
> 
> Please do make a PR, thanks!
> 
> Also is there any documentation anywhere on why `\\?\` makes it work? 😅

Docs from msdn: https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx

Just want to know If you really want to fix the issue in melos? Because this is some kind of Windows specified + Dart FileSystem issue, this will be fixed automatically by https://github.com/dart-lang/sdk/issues/27825 If dart team slove It. Although the issue has been opened almost 6 years...

**Comment by alexmercerind** [comment]
I saw this thread on `dart-lang`'s repo, so I "sub-classed" few methods which I had to write for my project.
Few users had their files stored in deep directories which `File Explorer` could normally open, but dart couldn't.

https://github.com/harmonoid/harmonoid/blob/73414a55ed24d18cd4440badd0a9d09a9acc7e72/lib/utils/file_system.dart#L49-L88

But, I'm not sure if this is a long-path related issue. Hope it helps somehow.

**Comment by blaugold** [comment]
I don't think this is a path length issue. This is the error you get if the path is too long:
```
FileSystemException: Exists failed, path = 'C:\Users\gabriel\Dev\melos-long-paths\.dart_tool\melos_tool\packages\\abbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbbabbbbbbbbb' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:126:11)
#2      _File.createSync (dart:io/file_impl.dart:270:14)
#3      _generateTemporaryProjects (package:melos/src/commands/bootstrap.dart:415:17)
#4      _BootstrapMixin._linkPackagesWithPubFiles (package:melos/src/commands/bootstrap.dart:143:11)
#5      _BootstrapMixin.bootstrap.<anonymous closure> (package:melos/src/commands/bootstrap.dart:41:19)
#6      _BootstrapMixin.bootstrap.<anonymous closure> (package:melos/src/commands/bootstrap.dart:14:7)
#7      _Melos._runLifecycle (package:melos/src/commands/runner.dart:127:15)
#8      _BootstrapMixin.bootstrap (package:melos/src/commands/bootstrap.dart:11:12)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:79:5)
<asynchronous suspension>
#11     main (file:///C:/Users/gabriel/Dev/melos/packages/melos/bin/melos.dart:42:5)
<asynchronous suspension>
```

Is this issue still occurring?

**Comment by tcaravana** [comment]
I have the same problem. the only way to avoid the error is by disabling the parallelism but the project I use melos takes several minutes to run if I disable the parallelism.

Any way to solve this?

**Comment by blaugold** [comment]
@tcaravana Are you getting  exactly the same error? There is a different [issue](https://github.com/dart-lang/pub/issues/3420) with `pub get` and running it concurrently on Windows, that already has a fix, but it's not in stable yet.

**Comment by tcaravana** [comment]
Yes, this is the error we get on Windows development machines running melos bs:

```
FileSystemException: Deletion failed, path = 'C:\Users\x\x\.dart_tool\melos_tool' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
#0 _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1 FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:420:7)
#2 _CleanMixin.cleanWorkspace (package:melos/src/commands/clean.dart:30:42)
#3 _BootstrapMixin._linkPackagesWithPubFiles (package:melos/src/commands/bootstrap.dart:155:5)
<asynchronous suspension>
#4 _BootstrapMixin.bootstrap.<anonymous closure> (package:melos/src/commands/bootstrap.dart:36:13)
<asynchronous suspension>
#5 _Melos._runLifecycle (package:melos/src/commands/runner.dart:121:7)
<asynchronous suspension>
#6 CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#7 MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:70:5)
<asynchronous suspension>
#8 main (file:///C:/scr/flutter/.pub-cache/hosted/pub.dartlang.org/melos-2.1.0/bin/melos.dart:42:5)
<asynchronous suspension>
pub finished with exit code 255
```

But we also have some problems when we run the pipeline tasks in linux machines. The first error that usually pops in logs is:


```
 [module1]: Deletion failed, path = '/home/ec2-user/agent1/_work/_tool/Flutter/2.10.5-stable/linux/flutter/.pub-cache/hosted/pub.dartlang.org/pdf_text-0.5.0' (OS Error: No such file or directory, errno = 2)
[module1]: Deletion failed, path = '/home/ec2-user/agent1/_work/_tool/Flutter/2.10.5-stable/linux/flutter/.pub-cache/hosted/pub.dartlang.org/fl_chart-0.41.0' (OS Error: No such file or directory, errno = 2)
```

In the both cases we can avoid those problems disabling concurrency but melos would take like 40 minutes to run all pub gets.

**Comment by blaugold** [comment]
Thanks for the additional info. Seems like an issue that can be mitigated by just retrying the operation. [Here](https://github.com/dart-lang/pub/blob/c4e9ddc888c3aa89ef4462f0c4298929191e32b9/lib/src/io.dart#L367) is how `pub` does it.

**Comment by tcaravana** [comment]
Yes, usually we need to run 5 or 6 times to successfully bootstrap melos. But for every test run the need to rerun the pipeline for 5 or 6 times are making melos hard to keep. :(

There is an easy way to customize melos bootstrap to retry like the code you sent?

**Comment by blaugold** [comment]
I should be able to add a fix in the next few days.
