### ISSUE TITLE
request:  --parsable that shows relative paths, not absolute

### ISSUE THREAD

**Issue by lukepighetti** [invertase/melos#246]
As of today, we can list a parsable list of packages

```
melos list --all --scope=home_screen --include-dependencies --parsable
/Users/lukepighetti/development/lukepighetti/spike_melos_task/libraries/analysis
/Users/lukepighetti/development/lukepighetti/spike_melos_task/features/home_screen
/Users/lukepighetti/development/lukepighetti/spike_melos_task/libraries/styles
/Users/lukepighetti/development/lukepighetti/spike_melos_task/libraries/widgets
```

However, you cannot feed these into `git sparse-checkout set /Users/lukepighetti/development/lukepighetti/spike_melos_task/libraries/analysis...`, it doesn't recognize absolute paths

If instead, we could get a parsable list of relative paths, such as 

```
melos list --all --scope=home_screen --include-dependencies --parsable-relative
libraries/analysis
features/home_screen
libraries/styles
libraries/widgets
```

Then we could pipe these into commands like `git sparse-checkout set libraries/analysis features/home_screen libraries/styles libraries/widgets`

**Comment by Salakar** [comment]
Landing in #257 , e.g.:

```
 melos list --all --include-dependencies --parsable --relative
```
