### ISSUE TITLE
fix:  failed load pubspec.yaml if contains dependencies from self hosted pub

### ISSUE THREAD

**Issue by amondnet** [invertase/melos#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

1.2.1

### Description

https://github.com/j4qfrost/pubspec/issues/3

> The issue is in the [`ExternalHostedReference`](https://github.com/j4qfrost/pubspec/blob/master/lib/src/dependency.dart#L115) parsing. The hosted reference can take [two forms](https://dart.dev/tools/pub/dependencies#hosted-packages), neither of which matches the JSON serialization in this package.
> 
> ## With `sdk: >=2.15.0`
> ```yaml
> dependencies:
>   transmogrify:
>     hosted: https://some-package-server.com
>     version: ^1.4.0
> ```
> 
> ## Pre-2.15.0
> ```yaml
> dependencies:
> ```

### Steps to reproduce

```yaml
dependencies:
  transmogrify:
    hosted: https://some-package-server.com
    version: ^1.4.0
```

`melos bootstrap`

```
Unhandled exception:
Bad state: expecting only one entry for dependency
#0      new DependencyReference.fromJson (package:pubspec/src/dependency.dart:19:9)
#1      new PubSpec.fromJson.<anonymous closure> (package:pubspec/src/pubspec.dart:103:68)
#2      JsonParser.mapValues.<anonymous closure> (package:pubspec/src/json_utils.dart:113:45)
#3      MapMixin.forEach (dart:collection/maps.dart:123:13)
#4      JsonParser.mapValues (package:pubspec/src/json_utils.dart:112:7)
#5      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:103:15)
#6      PubSpec.loadFile (package:pubspec/src/pubspec.dart:121:15)
<asynchronous suspension>
#7      PackageMap.resolvePackages.<anonymous closure> (package:melos/src/package.dart:368:25)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#9      PackageMap.resolvePackages (package:melos/src/package.dart:365:5)
<asynchronous suspension>
#10     MelosWorkspace.fromConfig (package:melos/src/workspace.dart:57:25)
<asynchronous suspension>
#11     _BootstrapMixin.bootstrap (package:melos/src/commands/bootstrap.dart:5:23)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:82:5)
<asynchronous suspension>
#14     main (file:///Users/amond/.pub-cache/hosted/pub.dartlang.org/melos-1.2.1/bin/melos.dart:10:5)
<asynchronous suspension>

```

### Expected behavior

melos should resolve dependencies

### Additional context and comments

https://github.com/j4qfrost/pubspec/pull/4

**Comment by Rannie** [comment]
same issue

**Comment by ekasetiawans** [comment]
For now, we can override pubspec dependency to this git repository https://github.com/amondnet/pubspec
then activate melos from source path.

**Comment by ekasetiawans** [comment]
We should update the pubspec version to 2.1.0 to solve this
https://pub.dev/packages/pubspec/changelog

**Comment by amondnet** [comment]
https://github.com/invertase/melos/pull/254
