### ISSUE TITLE
request: specify "since" for commits to include in gitlog with `melos version`

### ISSUE THREAD

**Issue by ragingsquirrel3** [invertase/melos#252]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

melos version --since=1.2.3

### Description

Let me know if there is a way to do this already/workaround now that I'm missing.

As a melos user, I want to control which entries are added to changelogs when running `melos version` to automatically update changelogs from conventional commits. If I run this now, it includes a bunch of very old commit logs and it's not clear to me how it decided to choose these. Maybe this would work better if I had been using this before, but I do not understand how to migrate to using this given there are a bunch of old commits.

It seems like it would help if I could specify a git tag or something to say "start including commits from here to include in the changelogs" so I could make it ignore older commits. Or, some way to solve this problem.

### Reasoning

Easier to migrate to melos.

**Comment by Salakar** [comment]
This is already supported in the global filters, see: https://melos.invertase.dev/filters#--since
