### ISSUE TITLE
request: Configurable prefix before conventional commit title

### ISSUE THREAD

**Issue by spydon** [invertase/melos#258]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

In some collaborative version control services, like Azure DevOps, they add an annoying non-configurable prefix to each merged pull requests commit message. 

For example: `Merged PR 404: fix: Use correct path for signing`

This feature would implement so that it is possible to ignore that prefix, maybe with a regex, to be able to version melos projects that are hosted by services with these prefixes properly.

### Reasoning

It would be useful since it would be possible to use Melos in services that are using these kind of prefixes.

### Additional context and comments

[Feature request for Azure Devops](https://developercommunity.visualstudio.com/t/change-default-title-for-pull-request-commits-to-n-1/365716)

**Comment by Salakar** [comment]
> @Salakar could I work on a PR for this? If that is the case, could you give some pointers to how you'd want it implemented? 🙂

Of course! Best place to start would be the conventional commits package: https://github.com/invertase/melos/tree/main/packages/conventional_commit - if the goal is to just ignore the prefix then it should be pretty straightforward modifying the regex to handle it. If it needs to be configureable then could probably add it as a optional named arg to `tryParse`: https://github.com/invertase/melos/blob/main/packages/conventional_commit/lib/conventional_commit.dart#L75 . Package has pretty good test coverage so should be hard to break things without it being detected.

**Comment by Salakar** [comment]
I mean technically removing the `^` from the start of the regex also solves this problem :D https://github.com/invertase/melos/blob/main/packages/conventional_commit/lib/conventional_commit.dart#L19

**Comment by spydon** [comment]
> I mean technically removing the `^` from the start of the regex also solves this problem :D https://github.com/invertase/melos/blob/main/packages/conventional_commit/lib/conventional_commit.dart#L19

Hahah here I was imagining a few hours of work at least. 😅 
That sounds like a good solution to me at least!

**Comment by as19ish** [comment]
Can we add support for bitbucket ? In bitbucket also when we try to merge PR it add this message as default.
Merged in feature/DM-175-tag-management (pull request #156)
