### ISSUE TITLE
Simplify scripts that are meant to be executed on multiple packages

### ISSUE THREAD

**Issue by lukepighetti** [invertase/melos#266]
If I try to use `select-package.dir-exists` to scope a command to only packages that contain the `ios` directory, when I try to run the command it gives me a user prompt instead of running it on all packages like `melos exec --dir-exists="ios"`

```yaml
  upgrade:pods:
    select-package:
      dir-exists: 'ios'
    run: |
      rm -rf Pods Podfile.lock
      pod repo update
      flutter precache --ios
      pod install
```

The user prompt it creates instead of running on all of them automatically

```bash
% melos upgrade:pods
Select a package to run the upgrade:pods script:

1) * [Default - Press Enter]
2) example
3) ml_pose_detection
4) timeline_player
5) tonal
6) tonal_ar


? Enter your choice 
```

**Comment by blaugold** [comment]
You can skip the prompt with the `--no-select` option.

**Comment by lukepighetti** [comment]
That runs the default, which only appears to be a single package

**Comment by blaugold** [comment]
Ah, I see. You need to use `melos exec` in `run`:
```yaml
  upgrade:pods:
    select-package:
      dir-exists: 'ios'
    run: |
      melos exec -- \
      rm -rf Pods Podfile.lock && \
      pod repo update && \
      flutter precache --ios && \
      pod install
```

It's not the nicest syntax because it needs to be a single command. There is some room for improvement here :)
