### ISSUE TITLE
fix:  can't run melos --version unless pwd is a directory with melos.yaml

### ISSUE THREAD

**Issue by lukepighetti** [invertase/melos#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

1.5.2

### Description

can't run melos --version unless pwd is a directory with melos.yaml

### Steps to reproduce

1. `cd /tmp && melos --version`

### Expected behavior

Show the version

**Comment by Salakar** [comment]
@cabljac and this one too thanks 🤓
