### ISSUE TITLE
fix: Missing logo in the docs header

### ISSUE THREAD

**Issue by MarkOSullivan94** [invertase/melos#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

1.5.2

### Description

Noticed whenever loading up the docs that the logo was missing.

### Steps to reproduce

1. Go to the docs homepage
2. Look at top left of docs homepage where the logo header is located

### Expected behavior

Expected to see the logo

### Screenshots

<img width="354" alt="Screenshot 2022-04-27 at 15 31 37" src="https://user-images.githubusercontent.com/6950843/165542763-329598ef-91f9-467f-9dd8-5475ee4f665c.png">

**Comment by Salakar** [comment]
Yep, github made changes to the raw API which broke this, fixed in https://github.com/invertase/docs.page/pull/182 which is deploying currently, thanks!
