### ISSUE TITLE
Remove dependency overrides from `pubspec_overrides.yaml` while publishing

### ISSUE THREAD

**Issue by blaugold** [invertase/melos#287]
`pub publish` does not allow dependency overrides (either in `pubspec.yaml` or `pubspec_overrides.yaml`) for the following reason:
```
* Your pubspec.yaml must not override non-dev dependencies.
  This ensures you test your package against the same versions of its dependencies
  that users will have when they use it.
```
This does not quite work for the development workflow of Melos, though.

We can simply remove all dependency overrides that come from melos before we invoke `pub publish` and then revert that change once publishing is done.

In general, it would make sense to add support for bootstrapping without local dependency overrides, to for example allow for testing against published versions.

**Comment by Salakar** [comment]
>   This ensures you test your package against the same versions of its dependencies
  that users will have when they use it.

I mean this message in the case of Melos is invalid really since it is the same versions that the user will use 😭 is there a case for allowing this in `pub` instead, if `pubspec_overrides.yaml` exists and was generated by a tool

> In general, it would make sense to add support for bootstrapping without local dependency overrides, to for example allow for testing against published versions.

I don't think this would work in Melos since the versions of dependencies local to the workspace (that are to be published) in each of the pubspecs won't exist on pub yet (because we're about to publish them all) so overrides are required otherwise unable to `pub get`, e.g.:

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/5347038/165739029-3e2b6dc4-626f-4136-806c-8977c7c0dd92.png">

**Comment by blaugold** [comment]
> I mean this message in the case of Melos is invalid really since it is the same versions that the user will use 😭 is there a case for allowing this in pub instead e.g. if pubspec_overrides.yaml exists and was generated by a tool, since the reason for this check does not much this case to start with

I think the case against that is that having different semantics for the `dependency_overrides` field in `pubspec.yaml` and `pubspec_overrides.yaml` is unintuitive and if `pubspec_overrides.yaml` is generated/edited by a tool it's easy to temporarily remove the overrides. 🙃  That it's safe to have dependency overrides while publishing is kind of specific to Melos because packages are usually versioned and published together and is highly automated.

> I don't think this would work in Melos since the versions of dependencies local to the workspace (that are to be published) in each of the pubspecs won't exist on pub yet (because we're about to publish them all) so overrides are required otherwise unable to pub get or even pub publish since it won't pass checks (current melos behaviour which generates the package_config.json files etc avoids this, but then we have all the other issues and I don't think we should be relying on both methods of resolution/overrides, just seems super hacky);

Maybe I don't understand something here, but do we need dependency overrides for publishing? Packages are sorted topologically and publish sequentially, so when a package is published, all dependencies should have already been published.

When I was writing this issue, I thought about the fact that there is currently no way to remove the `pubspec_overrides.yaml` files that melos generates except manually. But that really should have been implemented in `melos clean`.

**Comment by blaugold** [comment]
Closing this issue, since it is obsolete because of this [PR](https://github.com/dart-lang/pub/pull/3419), which ignores `pubspec_overrides.yaml` for the `pub publish` command.

**Comment by long1eu** [comment]
https://pub.dev/packages/google_sign_in_dartio
