### ISSUE TITLE
fix: Could not find a file named "pubspec.yaml" 

### ISSUE THREAD

**Issue by btrautmann** [invertase/melos#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.1.0

### Description

During `melos bs` we're seeing consistent failures:

```console
Could not find a file named "pubspec.yaml" in "/Users/brandontrautmann/.pub-cache/hosted/pub.dartlang.org/shared_preferences_android-2.0.11".
pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/brandontrautmann/.pub-cache/hosted/pub.dartlang.org/shared_preferences_android-2.0.11".)
```

We only just started noticing this because we began running on `macos` runners using Github Actions for some various workflows. We were then able to reproduce locally on `macos` by doing a `pub cache clean` and doing `melos bs`. This issue does not happen on our `ubuntu-latest` runners on Github Actions, so I suspect it's OS dependent.

**Important: This does _not_ happen with `v1.5.2`**

I have not had time to pull `melos` locally and do a `git bisect` between `1.5.2` and `2.x`, unfortunately, so hoping y'all can or have a hunch that doesn't even necessitate that.

### Steps to reproduce

On MacOS:

_Edited after posting to fix ordering_

1. `pub cache clean`
2. activate `melos 2.x` via `dart pub global activate`
3. `melos bs`
4. Note: we noticed this happen often with `git` hosted dependencies, but also see it on normal pub.dev dependencies

### Expected behavior

When running `melos bs`, it should complete successfully on MacOS.

**Comment by blaugold** [comment]
We recently started to run `pub get` in parallel, to speed up bootstrapping. Running `pub get` concurrently should be fine for Dart `2.16.0` and up, but there seem to be some issues with it. You can disable this behavior with the [`command/bootstrap/runPubGetInParallel`](https://melos.invertase.dev/configuration/overview#commandbootstraprunpubgetinparallel) option in `melos.yaml`.

I'm not sure if I understand the steps to reproduce. If I run `dart pub cache clean` that removes `~/.pub-cache` including the `bin` directory where the melos executable is. I just get `zsh: command not found: melos` after that. 🤔

**Comment by btrautmann** [comment]
> We recently started to run `pub get` in parallel, to speed up bootstrapping. Running `pub get` concurrently should be fine for Dart `2.16.0` and up, but there seem to be some issues with it ([dart-lang/pub#3404](https://github.com/dart-lang/pub/issues/3404)).
> 
> You can disable this behavior with the [`command/bootstrap/runPubGetInParallel`](https://melos.invertase.dev/configuration/overview#commandbootstraprunpubgetinparallel) option in `melos.yaml`.
> 
> I'm not sure if I understand the steps to reproduce. If I run `dart pub cache clean` that removes `~/.pub-cache` including the `bin` directory where the melos executable is. I just get `zsh: command not found: melos` after that. 🤔

Sorry about that, you're right. You'll need to activate melos again, I should have swapped steps 1 and 2 from my reproduction steps.

**Comment by btrautmann** [comment]
Update: Using the following does resolve this issue:
```
command:
  bootstrap:
    runPubGetInParallel: false
```
So it looks like it _is_ an issue when running in parallel. That does makes sense, as the `pubspec.yaml` that was not found _did_ exist in the directory that was supposedly searched, so I suspect it was some kind of race issue.

**Comment by blaugold** [comment]
Thanks for the update. It seems like `pub` considers a package to be in the cache once the directory exists, but does not check if it's fully unpacked.

Since there is a workaround, and it's nothing that can be fixed in Melos, can we close this issue?

**Comment by btrautmann** [comment]
> Since there is a workaround, and it's nothing that can be fixed in Melos, can we close this issue?

I'm confused.. Sorry if I didn't read your message above thoroughly enough. We're running this using `flutter 2.10.4` (`dart 2.16.2` and having issues only on macos. It doesn't seem like it's a `pub` issue since disabling parallel fixes the issue, it seems more likely an issue with the parallel implementation, unless I'm not understanding correctly.

**Comment by blaugold** [comment]
😁 Sorry if I was not clear enough. Before Dart 2.16.0 there was a bug that did not allow running `dart pub get` concurrently, but according to the Dart SDK changelog this should have been fixed:

> Fixed race conditions in `dart pub get`, `dart run` and `dart pub global run`. It should now be safe to run these concurrently.

Apparently, the fix did not fully resolve the bug and there is a related issue in the `pub` repo, which I mention [here](https://github.com/invertase/melos/issues/289#issuecomment-1117537199).

**Comment by btrautmann** [comment]
Ahhhh thanks for clarifying haha. Cool, we can track that issue and close this one for now 🙃 Thank you!

**Comment by ivan-dubovenko-m10** [comment]
- `flutter clean`
- `pub cache clean`
- `dart pub global activate melos`
```
command:
  bootstrap:
    runPubGetInParallel: false
```

Does not resolve the issue.

> Could not find a file named "pubspec.yaml" in ".../mobile-flutter/packages/features/request_funds".

After pulling repo, the package `/features/request_funds` was deleted from the project. But melos still looking for it.  

melos clean also fails with the same error. Actually I cant run any melos command in project dir, even `--version`, as it fails with this error

```
melos --version
3.0.1

dart --version
Dart SDK version: 2.19.5 (stable)

flutter --version
Flutter 3.7.8 • channel stable 
```

p.s. flutter pub get also fails:

```
flutter pub get
Running "flutter pub get" in mobile-flutter...
Warning: pubspec.yaml has overrides from pubspec_overrides.yaml
Resolving dependencies... 
Could not find a file named "pubspec.yaml" in "...mobile-flutter/packages/features/request_funds".
pub get failed
```

**Comment by ivan-dubovenko-m10** [comment]
Deleting `pubspec_overrides` in project root resolve it.
