### ISSUE TITLE
Question: Bootstrap without linking?

### ISSUE THREAD

**Issue by btrautmann** [invertase/melos#297]
Hi all 👋 

We've been using `melos` for a while now, and it's been great for us since we have 27+ packages that we ship as part of our app. However, since we mostly use path references but DON'T care about linking for the purposes of versioning or publishing our packages (we move OSS packages out to their own repository), we actually _don't_ want the linking to happen during `bootstrap`. However, the run configuration generation _is_ a nice to have, especially for melos scripts within the `melos.yaml`.

With that in mind, is there a way to run `bootstrap` _without_ linking? If not, is there a way to _just_ generate run configurations (and anything else that bootstrap does that I may be missing!).

**Comment by Salakar** [comment]
Wait I think I may have misunderstood, you meant IntelliJ run configurations instead right? 😅 So generate those only but don't link packages?

If so we could probably add a flag/melos config item for this - what do you think about this @blaugold?

**Comment by btrautmann** [comment]
Yeah, sorry, I should have been more clear!

We can definitely bypass `bootstrap` with a script that does `melos exec --flutter -- flutter pub get && melos exec --no-flutter -- dart pub get`. I guess my primary concern is that in doing so, we might miss out on other sub-steps added to `bootstrap`, the first of which is the generation of Intellij run configurations.

So I guess my initial question was, can we still `bootstrap` but bypass linking (e.g `melos bs --no-linking`)? This would be more "future-proof" in that it would bypass the one step we _don't_ want but include everything else (like run config generation).

As a last resort, having a command that _just_ generates run configurations would be fine, but that would mean you'd have to do the same for any new sub-step apart from linking added to `bootstrap` in the future. 

It's cool if the answer for right now is "no", we can kick the can down the road until we notice something more important that we're missing out on. I just figured I'd ask. The workaround of having a script that does `flutter pub get` and `dart pub get` in place works for our _current_ needs.

**Comment by blaugold** [comment]
Maybe I'm missing something, but what is the problem with bootstrapping path references?

**Comment by btrautmann** [comment]
> Maybe I'm missing something, but what is the problem with bootstrapping path references?

Sorry, good question. And maybe that's the crux of the issue. The problem we're facing is that the output on a single package from `melos bs` and `flutter pub get` are different (which is probably expected based on what linking aims to achieve). This (I believe) means that we always have to `bs` instead of using native flutter tooling if we don't want to create a diff in our `pubspec.lock` files (we commit these, because (pretty much) all packages within our monorepo roll up to build an application itself). This _might_ be fine using something like the `--scope` option but it forces devs to use `melos` in cases where it seems unnatural, rather than just doing a `flutter pub get`.

This may point to a deeper concept in that `melos` seems to be more aimed at serving repos such as FlutterFire (independent packages released for their own purpose) rather than an "app" monorepo. Let me know if I'm mistaken.

**Comment by blaugold** [comment]
Ah, I see. This is a good reason to migrate to enabling `command/bootstrap/usePubspecOverrides`. We still have to document this feature properly, but [this comment](https://github.com/invertase/melos/issues/117#issuecomment-1125224468) describes the basics.

This makes the dependency overrides created by `melos bs`  "permanent" in the sense that running `flutter pub get` does not revert them. In fact, `flutter pub get` is executed in place during bootstrapping, just like if you manually run `flutter pub get` in the package root. There should be no differences in the lock file between running `melos bs` and `flutter pub get`.

You don't even need path dependencies when enabling this option. You can just use `foo: any` for private local packages.

As a side note, lock files of dependencies don't figure into how dependencies of the package, in which `pub get` is executed, are resolved, so only the lock file of the app needs to be committed, but I might not fully understand the context.

**Comment by btrautmann** [comment]
Oh, this is super helpful! Once we're on Flutter 3/Dart 2.17.0 we'll definitely look into that option. In the meantime, based on the comment you linked, it sounds like the behavior we're seeing is _expected_, though maybe not _desired_. We hadn't been aware that there was already an expectation in place to run `flutter pub get` after bootstrapping. That makes sense now.

RE: `pubspec.lock` files. I've suspected for a while that we could optimize which lock files were committed, but I'm still having a hard time understanding what you've stated above.

By example - for any of the "support" (non-app) packages we have in the repo, if I delete the pubspec.lock file (this would be akin to a new developer cloning the repository where the same lock file is _not_ added to the repo), and then run `flutter pub get`, the versions placed in the lock file will be the same or _greater_ than the ones in the version I had deleted. In other words, this is like an implicit `flutter pub upgrade`. My concern here is that if we don't commit/delete the lock files from the repo, we could run into cases where developers working on the same supporting packages that contribute to the same overall app are working on different versions of underlying dependencies. Am I thinking about this incorrectly?

**Comment by blaugold** [comment]
> We hadn't been aware that there was already an expectation in place to run flutter pub get after bootstrapping. That makes sense now.

Maybe it's just a typo, but it is important to run `flutter pub get` in all Flutter packages **before** bootstrapping, **not after**. Otherwise, with the current default behavior the overrides aren't effective after running `flutter pub get`, but if you only have path dependencies that probably is not noticeable.

> RE: pubspec.lock files. I've suspected for a while that we could optimize which lock files were committed, but I'm still having a hard time understanding what you've stated above.

What I meant to say is that if you have package `B` which depends on package `A`, a lock file in package `A` does not affect dependency resolution when running `pub get` in package `B`, but it makes sense to commit lock files to ensure testing of individual support packages uses deterministic versions. I guess for packages which are published it is more important to test against the latest version of dependencies, at least that seems to be the recommendation on [`dart.dev`](https://dart.dev/tools/pub/glossary#library-package).

**Comment by btrautmann** [comment]
Ok, I _think_ we're mostly on the same page then. I suspect we will avoid actually invoking `bootstrap` for now, until we're on dart 2.17.0 and we can use `usePubspecOverrides`. The requirement to need to run `flutter pub get` prior to bootstrap is definitely something we haven't been doing, which may be why we were seeing issues, but either way it's simplest for us to simply `melos exec` our pub gets until we can bootstrap and not run into diffs.

Thanks for the super quick response time and careful clarifications. It's HIGHLY appreciated. Going to close this issue as I think the `usePubspecOverrides` will address the root issue we were seeing.
