### ISSUE TITLE
fix:  system command call error when trying to run Melos through FVM and using --sdk-path

### ISSUE THREAD

**Issue by michte** [invertase/melos#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.3.1

### Description

Hi,

Due to team practices' constraints, I have to make multiple versions of the Flutter SDK available without exposing the `flutter` or `dart` commands in the system `PATH` environment variable to avoid confusion. I ended using FVM which works quite well with single package projects, but I ended having problems using it with Melos and multi-package projects.

As I needed to pass to Melos the sdk in order to run its commands, I added the `--sdk-path` parameter with the documented value `.fvm/flutter_sdk`. But instead of properly running the command, Melos fails with an exception stating that "%1 is not a valid Win32 application" when trying to run `dart --version` (we are, obviously, running on Windows 😃 ).

Investigating a bit, it seems to come down to a missing `runInShell` boolean parameter in the `currentDartVersion` method in `packages/melos/lib/src/common/utils.dart` which would properly call the `dart --version`, even with the missing `.bat` extension in a Windows environment.

Using a standard configuration (`flutter`, `dart` and `melos` commands in the PATH), Melos commands execute successfully.

### Steps to reproduce

1. Setup FVM
2. Configure the project to use the desired Flutter SDK version using FVM (v2.10.5)
3. Launch a Melos command through FVM: `fvm flutter pub global run melos bootstrap --sdk-path=.fvm/flutter_sdk`
4. The command fails with the following output:

```shell
PS D:\***\projet> fvm flutter pub global run melos bootstrap --sdk-path=.fvm/flutter_sdk
melos bootstrap
   └> D:\***\projet

Running "D:\***\projet\.fvm/flutter_sdk\bin\flutter pub get" in workspace packages...
Unhandled exception:
ProcessException: %1 n’est pas une application Win32 valide.

  Command: D:\***\projet\.fvm/flutter_sdk\bin\dart --version
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      currentDartVersion (package:melos/src/common/utils.dart:118:26)
#6      MelosWorkspace.canRunPubGetConcurrently (package:melos/src/workspace.dart)
#8      _BootstrapMixin._linkPackagesWithPubFiles (package:melos/src/commands/bootstrap.dart:146:35)
<asynchronous suspension>
#9      _BootstrapMixin.bootstrap.<anonymous closure> (package:melos/src/commands/bootstrap.dart:41:13)
<asynchronous suspension>
#10     _Melos._runLifecycle (package:melos/src/commands/runner.dart:127:7)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:79:5)
<asynchronous suspension>
#13     main (file:///C:/Users/***/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/melos-2.3.1/bin/melos.dart:42:5)
<asynchronous suspension>
pub finished with exit code 255
```

### Expected behavior

The Melos bootstrap command should execute successfully.

**Comment by blaugold** [comment]
Thanks for this detailed report. We already have a related PR (#300), but I wasn't sure what exactly the issue was. This makes sense now.
