### ISSUE TITLE
When not specifying a melos.yaml, master channel causes a "pubspec.yaml has no lower-bound SDK constraint."

### ISSUE THREAD

**Issue by rrousselGit** [invertase/melos#32]
Related to #26

When no `melos.yaml` is specified, running `melos bootstrap` can throw:

```yaml
pubspec.yaml has no lower-bound SDK constraint.
You should edit pubspec.yaml to contain an SDK constraint:

environment:
  sdk: '>=2.10.0 <3.0.0'

See https://dart.dev/go/sdk-constraint
pub get failed (65; See https://dart.dev/go/sdk-constraint)
 
Bootstrap failed, reason: pub get failed, see logs above.
```

when using the master channel of Flutter.

Here's a project to reproduce this exception:

https://github.com/rrousselGit/ci/tree/366796889f59fbb07fa45cf790f067e675e3f4de

Make sure to use the master channel.

**Comment by Salakar** [comment]
Hey, pushed a fix for this and it's now live in the latest version.

Thanks
