### ISSUE TITLE
`melos bootstrap` command sometimes takes very long 

### ISSUE THREAD

**Issue by nilsreichardt** [invertase/melos#322]
I'm not sure if this is a Melos issue or a Flutter issue, but the [FlutterFire](https://github.com/firebase/flutterfire) repository has sometimes the issue that the `melos boostrap` takes very. This makes the [FlutterFire](https://github.com/firebase/flutterfire) CI flaky. The chance for this is 1 - 5%. You find the logs in the following PR: https://github.com/firebase/flutterfire/pull/8916 (keep in mind that the logs will be deleted by GitHub in 90 days).

* https://github.com/nilsreichardt/flutterfire/runs/6887635553?check_suite_focus=true
* https://github.com/nilsreichardt/flutterfire/runs/6887680143?check_suite_focus=true
* https://github.com/nilsreichardt/flutterfire/runs/6887693001?check_suite_focus=true
* https://github.com/nilsreichardt/flutterfire/runs/6887701442?check_suite_focus=true
* https://github.com/nilsreichardt/flutterfire/runs/6887696867?check_suite_focus=true

**Comment by nilsreichardt** [comment]
Thanks, @blaugold. I will try out in the next days 👍

**Comment by nilsreichardt** [comment]
This seems to fix it 🚀 I ran the jobs in total 1000x (each job 200x) and only the `analyze` job failed 2x (the e2e test does not count). Unfortunately, I can't access the logs anymore, because GitHub can't load the page (the page crashes). But I think these failed runs are different issues.
 
![image](https://user-images.githubusercontent.com/24459435/174012638-c4e4f625-6513-43ba-bcb7-fdd05a0336b6.png)

**Comment by akku1906** [comment]
We prepared a working patch that stabilizes `melos bootstrap` in CI  
(timeout + retry logic + early fail on inconsistent deps).  

In our tests it reduced run time by ~70% and eliminated random flakiness.  

Happy to share README + proof if there’s interest.
