### ISSUE TITLE
Melos Bootstrap overwrites all Intellij project config

### ISSUE THREAD

**Issue by josh-burton** [invertase/melos#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.5.0

### Description

I regular run `melos bootstrap` to update the project if I have added new packages or new execs.

This seems to overwrite all Intellij config for the project. For example I exclude the `.fvm/flutter_sdk` folder from indexing, but each time I run bootstrap I need to redo this.

Do we need a way to run a partial bootstrap? Would it be possible not to overwrite the entire config?

### Steps to reproduce

1. Mark a folder in the IntelliJ project as excluded
2. Run `melos bootstrap`
3. The folder is now included again

### Expected behavior

Some IntelliJ config should not be overwritten by bootstrap

**Comment by blaugold** [comment]
ATM, we are overwriting the `iml` files for modules every time IntelliJ files are generated. 

@Salakar Could we just write them if they don't already exist? The content always seems to be the same.

**Comment by Salakar** [comment]
> ATM, we are overwriting the `iml` files for modules every time IntelliJ files are generated.
> 
> @Salakar Could we just write them if they don't already exist? The content always seems to be the same.

This seems fine to me, only ones that should probably always write are the run configuration ones, all the project ones don't need to be rewritten everytime
