### ISSUE TITLE
Breaking changes for next major release

### ISSUE THREAD

**Issue by blaugold** [invertase/melos#355]
This issue is for collecting and discussing breaking changes for a future major release so that we can batch them and make it easier for users to migrate. We should create a migration guide when the time comes.

# Features to remove

- [x] `--since` filter option (https://github.com/invertase/melos/pull/454)
   - `--diff` (#323) does the same as `--since` but is more powerful. Having two options that have the same functionality can be confusing.

# Options to enable per default

These options have been successively added and were not enabled by default to not break things. They are generally useful features that most users will want to have enabled.

- [x] Enable `includeScopes` (#341).
- [x] Enable `linkToCommits` (#186), if repository is set.
- [x] Enable `workspaceChangelog` (#161).
- https://github.com/invertase/melos/pull/457

# Move to `dependency_overrides.yaml` and Dart `2.18.0`

We should consider removing support for bootstrapping with temporary packages and fully move to `pubspec_overrides.yaml`.

This would require moving to Dart `2.18.0` as the minimum supported version to ensure that publishing with `dependency_overrides.yaml` works without a workaround.

The advantages are:
- Users won't run into the issues related to temporary packages and get the improved integration with other tools.
- We don't have to maintain two mechanisms for bootstrapping.
- Between `2.12.0` and `2.18.0` a number of useful language features were added.

## To do

Tasks that need to be completed, if we decide to move to `dependency_overrides.yaml`.

- [x] Remove `usePubsecOverrides`.
- [x] Remove temporary packages bootstrapping mechanism.
- [x] Update docs to explain:
  - how bootstrapping uses `dependency_overrides.yaml` files.
  - that `dependency_overrides.yaml` should be ignored.
  - how `pub get` works in a bootstrapped workspace.
  - when `melos bootstrap` needs to be rerun.
- [x] Upgrade Dart version constraints.

# Rework hooks

- [x] #321.

# Local installation of Melos

- [x] https://github.com/invertase/melos/pull/431

# Rename config options to be consistent

- [x] https://github.com/invertase/melos/pull/462

# Fetch tags before versioning

- [x] https://github.com/invertase/melos/pull/461

**Comment by spydon** [comment]
Closing this since release already occurred.
