### ISSUE TITLE
fix: Error with postbootstrap command

### ISSUE THREAD

**Issue by ferraridamiano** [invertase/melos#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.6.0

### Description

I'm using melos postbootsrap command to generate the translations code (with `intl` package) for a flutter app. The command is pretty easy: `cd translations && flutter gen-l10n`. If I run `melos bootstrap` on linux everything works fine. If I run the same command on Windows I get the following error:
```
melos run postbootstrap
  └> cd translations && flutter gen-l10n
     └> FAILED
ScriptException: The script postbootstrap failed to execute
```
Of course I know that I have to execute it with cmd and not with powershell since the latter does would give a syntax error because the `&&`. If I run that command manually from cmd I get no error.

### Steps to reproduce

I created an example repository in order to show the issue. I also setup github action with both linux and windows runners in order to show the different behaviours. You can see the different output in the CI [here](https://github.com/ferraridamiano/monorepo_example/actions/runs/2979355289).

Otherwise you can reproduce it locally on a Windows PC:
1. Clone the repo on Windows: `git clone https://github.com/ferraridamiano/monorepo_example`
2. Run `melos bootstrap`

### Expected behavior

Same behaviour on Linux and Windows

**Comment by blaugold** [comment]
Thanks for the detailed report! I've got a fix in #369.
