### ISSUE TITLE
Allow viewing usage description with `-h` when outside a Melos workspace 

### ISSUE THREAD

**Issue by blaugold** [invertase/melos#376]
Currently, Melos always reports an error when invoked outside a Melos workspace. To explore Melos commands, it's useful to be able to view the usage description outside a Melos workspace.

**Comment by VoidCupboard** [comment]
Hi! Can I work on this issue?

**Comment by blaugold** [comment]
Sure, go ahead!

**Comment by SscSPs** [comment]
Hey, I created a PR for this, I checked VoidCupboard's fork and didn't find any work on this, so i worked on it and submitted a PR, 
Please review it @blaugold
