### ISSUE TITLE
fix:  Crash while running command

### ISSUE THREAD

**Issue by KirkBushman** [invertase/melos#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.7.1

### Description

Melos crashes on CI, with logs: 

```
Unhandled exception:
Null check operator used on a null value
#0      _RunMixin._runScript (package:melos/src/commands/run.dart:136:[10]
<asynchronous suspension>
#1      _RunMixin.run (package:melos/src/commands/run.dart:23:22)
<asynchronous suspension>
#2      RunCommand.run (package:melos/src/command_runner/run.dart:53:14)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:[13]
<asynchronous suspension>
#4      MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:80:5)
<asynchronous suspension>
#5      main (file:///Users/runner/hostedtoolcache/flutter/stable-3.3.3-x64/.pub-cache/hosted/pub.dartlang.org/melos-2.7.1/bin/melos.dart:44:5)
<asynchronous suspension>
Error: Process completed with exit code 255.
```

the command is this one: 

`melos exec --fail-fast -- \
      flutter pub run build_runner build --delete-conflicting-outputs`

### Steps to reproduce

1. run the command
2. see the crash

### Expected behavior

should not crash

**Comment by matejhocevar** [comment]
Hey @blaugold! Thank you for fixing this. 💪

I can see that PR was already merged into the main.
Is there any ETA for when the new release it's going to be available?

**Comment by blaugold** [comment]
Usually, there is a new release every 1 to 2 weeks.
