### ISSUE TITLE
request:  add support for self-hosted gitlab

### ISSUE THREAD

**Issue by MobiliteDev** [invertase/melos#392]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Many companies use self-hosted repo like gitlab with a private URL.

Is it planned to support self-hosted repositories ?

### Reasoning

My company is using a gitlab self-hosted instance and I would like to activate the [linkToCommits](https://melos.invertase.dev/configuration/overview#commandversionlinktocommits) option

**Comment by Anikalp1** [comment]
@Salakar @MobiliteDev I want to work on this, please assign it to me.

**Comment by Almighty-Alpaca** [comment]
Has there been any progress on this? If not I'd really like to take a look at this too since I'm currently starting to work on a project that would benefit from supporting self-hosted GitLab repositories.

**Comment by blaugold** [comment]
I haven't heard anything from @Anikalp1 yet, and he hasn't forked the repository, so don't think he has started working on this issue. 

@Almighty-Alpaca You can go ahead and create a PR.
