### ISSUE TITLE
request:  Add the possibility to show the version date in the changelog

### ISSUE THREAD

**Issue by MobiliteDev** [invertase/melos#393]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Add an option like [linkToCommits](https://melos.invertase.dev/configuration/overview#commandversionlinktocommits) for adding the date in the changelog when publishing a new version

### Reasoning

The date could be an interesting information in the changelog to understand sometimes some bugs, or to know if the library is on date

**Comment by bhattabhi013** [comment]
Hi,
I'll like to work on this. How can I test the changes I'll be making?

**Comment by blaugold** [comment]
Tests for changelog generation are in [`changelog_test.dart`](https://github.com/invertase/melos/blob/main/packages/melos/test/changelog_test.dart). 

Let me know if you need more help with adding tests.

**Comment by mzdm** [comment]
I wil try to take a look at it over the weekend
