### ISSUE TITLE
request:  Add `Contributing.md` in the repo

### ISSUE THREAD

**Issue by bhattabhi013** [invertase/melos#394]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

NA

### Description

Add `Contributing.md` file that consists of contributing guidelines for the project.

### Reasoning

This will increase the contributors and will improve the overall aspects of project.

**Comment by bhattabhi013** [comment]
I'll like to work on it, please assign

**Comment by Salakar** [comment]
If you make one please include https://github.com/invertase/melos#local-development-setup as part of the guide, thanks!

**Comment by keerthanasathya** [comment]
I would like to work on this

**Comment by blaugold** [comment]
@keerthanasathya Sorry, this issue is already assigned. There are still [unassigned issues](https://github.com/invertase/melos/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest+no%3Aassignee) left, though.

**Comment by blaugold** [comment]
Fixed by https://github.com/invertase/melos/commit/50b06016972903cd70364ed1f3df61e09f1b7daf
