### ISSUE TITLE
request: Untracked, local additions to pubspec_overrides.yaml

### ISSUE THREAD

**Issue by hacker1024** [invertase/melos#409]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

An untracked file called `melos_overrides.yaml` can be placed in the monorepo alongside the `melos.yaml` file. Melos will add the packages listed in this file to all generated `pubspec_overrides.yaml` files.

### Reasoning

It's convenient sometimes to use local copies of packages that are outside a monorepo, but being developed concurrently.

```
dependencyA/
dependencyB/
project/
├─ packageA/
├─ packageB/
├─ melos.yaml
```

These dependencies could be added to each monorepo package's `pubspec_overrides.yaml`.
Melos generates this file, and provides no option at the moment to add external packages in this fashion.

`melos_overrides.yaml`

```yaml
dependency_overrides:
  - ../dependencyA
  - ../dependencyB
```

**Comment by blaugold** [comment]
I think this feature makes sense.

Maybe the following info helps meanwhile:

- You can add `dependency_overrides` to `pubspec.yaml` files of individual packages and those will be merged into the generated `pubspec_overrides.yaml` file.
- You can directly add  `dependency_overrides` in `pubspec_overrides.yaml` files in addition to those added by Melos. Melos will only touch those dependencies listed in the `# melos_managed_dependency_overrides:` comment.

**Comment by hacker1024** [comment]
I have made a PR mostly implementing the feature discussed here. The one difference is that external paths cannot be used due to the design of the glob expression resolver, but this can be resolved with a symlink.
