### ISSUE TITLE
fix:  versions CHANGELOG output encoding broken on chinese commit

### ISSUE THREAD

**Issue by LaysDragon** [invertase/melos#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.7.1

### Description

if the commit message include chinese character,CHANGELOG output will garbled.

### Steps to reproduce

1. add conventional commits include a chinese message like `feat(example):這是一個測試`
2. run melos versions to build CHANGELOG and version commit.

### Expected behavior

The CHANGELOG output should be correct.

### Screenshots

![image](https://user-images.githubusercontent.com/10185394/196500208-86f6a358-67e7-48f8-be3e-ef12f464e889.png)
![image](https://user-images.githubusercontent.com/10185394/196500225-f56c3f18-1e17-4105-aff3-7ac690fa6e0c.png)

**Comment by Almighty-Alpaca** [comment]
This is due to the default stdout/stderr encoding affecting the output of `git log`.  I've provided a fix for this in #412.
