### ISSUE TITLE
Can't import from local packages

### ISSUE THREAD

**Issue by tim1230** [invertase/melos#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.7.1

### Description

Hey, so my plan is to develop an application consisting of 2 separate flutter apps and a package for shared logic. Which means that code I wanna use in both apps (e.g. api requests) will be placed in the package for shared logic. Then I wanna import and use it in the separate apps. Now what I did is following the melos documentation.

1. Installing melos
2. Creating the melos.yaml file
3. Adding the mentioned apps and files in the 'packages' folder
4. Running the bootstrap command
5. Initialized git repository

IDE: Visual Studio Code with Flutter, Dart and melos extensions
Machine: M1 Pro Mac Book Pro

Project Structure:
```
.idea
.git
packages
    shared
    app1
    app2
.gitignore
LICENSE
melos_project_name.iml
melos.yaml
README.md
```

Content of the melos.yaml file:
```
name: project_name

repository: LINK_TO_GITHUB

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true
```

Melos Bootstrap output:
```
Running "flutter pub get" in workspace packages...
  ✓ app1
    └> packages/app1
  ✓ shared
    └> packages/shared
  ✓ app2
    └> packages/app2
  > SUCCESS

Generating IntelliJ IDE files...
  > SUCCESS

 -> 3 packages bootstrapped
```

Until this point everything works fine.
Now from my understanding of the documentation I should be able to use functions and whatever from the 'shared' package in both of my Flutter apps without adding anything to my pubspec.yaml files, right? It doesn't work.
Also setting 'usePubspecOverrides' to false doesn't help.

The question is what did I configure wrong or did I misunderstand melos itself and my use case is not supported?

### Steps to reproduce

Follow the melos documentation, create 3 packages, bootstrap them and try to import anything from one package to another.
Look in the Description for details.

### Expected behavior

I should be able to import functions, etc. from on package to another.

**Comment by tim1230** [comment]
Update:
It looks like that the 'pubspec_overrides.yaml' file is not created by default on Mac (Apple Silicon) but it is on Windows. Also the import works perfectly fine on Windows. As soon as I try to run the working project on Mac the IDE says that the import target does not exist and the App also doesn't start.

```
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                            8.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/...

    Error: Couldn't resolve the package 'shared' in 'package:shared/example_api.dart'.
    lib/main.dart:2:8: Error: Not found: 'package:shared/example_api.dart'
    import 'package:shared/example_api.dart';
           ^
    lib/main.dart:107:34: Error: The method 'getExample' isn't defined for the class '_MyHomePageState'.
```

If I try to run melos bootstrap again the 'pubspec_overrides.yaml' file gets deleted.

**Comment by tim1230** [comment]
Update: After an extension update notification of Visual Studio Code (dart, flutter or melos idk)  showed up everything works fine now. I have absolutely no idea why but it does.

**Comment by subzero911** [comment]
+1, the same problem
melos v.2.9.0
config:
![image](https://user-images.githubusercontent.com/12999702/206905109-7c8dcc6c-a530-462f-82e1-a7e0cefc9a42.png)
(pushka is a head project, and models and helpers are sub-packages)

I did `melos bootstrap` and it found 3 packages successfully
![image](https://user-images.githubusercontent.com/12999702/206905175-cb2efede-2d70-4f54-ba77-a5e175a3551e.png)

But it still can't see `pushka` after `flutter pub get`
![image](https://user-images.githubusercontent.com/12999702/206905199-177d8825-93fd-4303-bb72-5401d2e10fd8.png)
