### ISSUE TITLE
request:  `melos analyze`

### ISSUE THREAD

**Issue by jpnurmi** [invertase/melos#424]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

```
melos analyze [--fatal-infos] [--[no-]fatal-warnings]
``` 

### Description

It would be nice to have a built-in Melos command for analyzing projects. The command should accept `--fatal-infos` and `--[no-]fatal-warnings` arguments.

### Reasoning

I think it would be useful because I have such a script for every project of mine using Melos. :wink:

### Additional context and comments

It's common for Melos projects to define a script that runs either `dart analyze` or `flutter analyze`, something like:
```yaml
analyze: melos exec -c1 -- flutter analyze --fatal-infos .
```

**Comment by blaugold** [comment]
I agree, I have the same experience! `format`, `test` and maybe `generate` (for build_runner) are similarly universally useful.

**Comment by jessicatarra** [comment]
I'm really interested in this feature request, and I might be able to contribute. But I'm not sure what the 'Accepted' tag means. I think it means that the feature request has been approved, but I'm not sure if someone is already working on it?

**Comment by spydon** [comment]
@jessicatarra it just means that we (the maintainers) also think this is a good idea, so if you want to contribute a PR implementing this feature, feel free! :)
