### ISSUE TITLE
fix: IOException when running melos bootstrap

### ISSUE THREAD

**Issue by ynnob** [invertase/melos#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.9.0

### Description

I created a empty directory with the `melos.yaml`:

```
name: Sloth

packages:
  # PLUGINS
  - packages/*

scripts:
  analyze:
    exec: dart analyze .

  upgrade:
    exec: dart pub upgrade .

```

The directory packages contains 2 fresh generated dart package projects. no code or dependecies added yet.

Running the command `melos bs` or `melos bootstrap` will result in an **IOException**:
```
Linking workspace packages...
IOException: Melos failed to delete entry because it was in use by another process.
This may be caused by a virus scanner or having a file
in the directory open in another application.
```

I am using visual studio code and this exception was already reported and supposedly fixed in PR #329 for issue #245

### Steps to reproduce

1. dart pub global activate melos
2. open visual studio code and create a new folder with projects in the packages folder
3.  run `melos bs` or `melos bootstrap`

### Expected behavior

Melos should succeed with the operation: Linking workspace packages.

### Screenshots

![melos_bug](https://user-images.githubusercontent.com/34171562/207945014-485bfcf4-fe65-4358-8cc3-c10074973bba.png)

### Additional context and comments

When i close vs code and run `melos bs` in the windows terminal i can successfully execute the command and no error is thrown.

Also i:
- tried to start vs code as admin -> not working
- deactivate melos, clear cache, install melos -> not working
- restarting my computer -> not working

Additionally after the execution of melos bs fails, vs code and widnows seem to strugle with the files in the folder. As long as vs code is open after the failed execution i could not rename the folder because package renaming operation failed and i could not delete the .dart-tools folder over the windows explorer because it was blocked as well.

**Comment by blaugold** [comment]
This is a Windows specific issue we have never been able to really fix. At this point, I don't know what Melos could do differently here.

The good news is that the issue only seems to happen with the current default bootstrapping mechanism. You can opt into the new bootstrapping mechanism by setting `command/bootstrap/usePubspecOverrides` to `true` and adding `pubspec_overrides.yaml` to your `.gitignore` file. In Melos 3.0.0, only the new mechanism will be available.

**Comment by ynnob** [comment]
Alright that seems to work! 
Thank you. Somehow i missed that. Because at some point i already added the pubspec_overrides.yaml to my gitignore file but never activated the feature.
