### ISSUE TITLE
fix:  unhandled melos version out of range exception

### ISSUE THREAD

**Issue by helightdev** [invertase/melos#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.9.0

### Description

Running `melos version` results in follwing exception:
```
Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 2
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      nextVersion (package:melos/src/common/versioning.dart:179:38)
#2      MelosPendingPackageUpdate.nextVersion (package:melos/src/common/pending_package_update.dart:122:20)
#3      _VersionMixin._logNewVersionTable.<anonymous closure> (package:melos/src/commands/version.dart:565:48)
#4      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#5      List.addAll (dart:core-patch/growable_array.dart:325:17)
#6      _VersionMixin._logNewVersionTable (package:melos/src/commands/version.dart:557:14)
#7      _VersionMixin.version (package:melos/src/commands/version.dart:277:5)
<asynchronous suspension>
#8      VersionCommand.run (package:melos/src/command_runner/version.dart:237:7)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     MelosCommandRunner.runCommand (package:melos/src/command_runner.dart:80:5)
<asynchronous suspension>
#11     main (file:///home/helight/.pub-cache/hosted/pub.dartlang.org/melos-2.9.0/bin/melos.dart:46:5)
<asynchronous suspension>
```
This seems to be a problem with the conventional commits parser.

### Steps to reproduce

1. Clone the repo https://github.com/DarwinFramework/dogs at commit efb8db2e20f1618e2d2514a3a3accd685ec46158
2. Run melos version
3. Observe the error

### Expected behavior

Skip the offending commit (?)

**Comment by helightdev** [comment]
The first time I observed this error was after commit ff2203430c45a75ef95a821b7bfb2b3790a51484

**Comment by blaugold** [comment]
The problem is [here](https://github.com/DarwinFramework/dogs/blob/efb8db2e20f1618e2d2514a3a3accd685ec46158/packages/dogs_darwin/pubspec.yaml#L3). Melos expect prerelease versions two have two components, so `1.0.1-alpha.0` instead of `1.0.1-alpha`. But Melos should not crash and provide a better error message.
