### ISSUE TITLE
Using the name key in melos same as a package name causes issues in bootstrap

### ISSUE THREAD

**Issue by Amplifiyer** [invertase/melos#47]
In `melos.yaml` if the `name` key is same as one of the dependent package's name (e.g. amplify_flutter in this case), running `melos bs` throws an error as below.

```sh
> amplify-flutter % melos bootstrap                                        
melos bootstrap
   └> /Users/pravgupt/Workspaces/Flutter/amplify-fork/amplify-flutter

Bootstrapping project...               |Running "flutter pub get" in .melos_tool...                     




Error on line 71, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
71 │   amplify_flutter: 
   │   ^^^^^^^^^^^^^^^
   ╵
pub get failed (65;    ╵)
 
Bootstrap failed, reason: pub get failed, see logs above.
```

The generated `pubspec.yaml` in `.melos_tool` dir is attached (file renamed to .txt) [pubspec.txt](https://github.com/invertase/melos/files/5767742/pubspec.txt)

To reproduce, pull down this repo https://github.com/aws-amplify/amplify-flutter and branch `amplify_core_refactor` and change the name in `melos.yaml` and run `melos bs`

**Comment by Salakar** [comment]
cc @dackers86 - could you fix this one; straightforward; https://github.com/invertase/melos/blob/master/packages/melos/lib/src/common/workspace.dart#L398 just prefix that, something like;

```dart
workspacePubspec['name'] = 'melos_workspace_$workspaceName';
```

**Comment by Salakar** [comment]
This has been fixed in the latest releases. Thanks
