### ISSUE TITLE
fix:  `melos --version` tries to downgrade when on a prerelease version

### ISSUE THREAD

**Issue by spydon** [invertase/melos#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.0.0-dev.0

### Description

When running `melos --version` it is looking for newer versions of Melos and it thinks that 2.9.0 is newer than 3.0.0-dev.0 which I'm currently on.

### Steps to reproduce

```
~ ❯ melos --version
3.0.0-dev.0
? There is a new version of melos available (2.9.0). Would you like to update? (Y/n) »
```

### Expected behavior

Reporting that I'm running the latest version, or that there is a new pre-release version out (when being on a pre-release version).

**Comment by blaugold** [comment]
`pub_updater` does not support handling prereleases yet, but meanwhile we could at least disable the update check for prerelease versions.

**Comment by renancaraujo** [comment]
@spydon I think this was fixed, can you still reproduce it?

**Comment by spydon** [comment]
Works like it should now!
