### ISSUE TITLE
fix: Incorrect vscode tasks generated after running melos scripts in package

### ISSUE THREAD

**Issue by tomwyr** [invertase/melos#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.9.0

### Description

Melos generates VSCode tasks (available under `⇧⌘B`) after running scripts from the `melos.yaml` file using the extension (`Run script` lens). If the script runs on a specific package, the generated task is incorrect and it fails when launched from the tasks panel.

### Steps to reproduce

- Create project with a package (e.g. `A`)
- Add script that can be run in `A`
- Run the script using the `Run script` lens
- Run generated task from the tasks panel `⇧⌘B`

### Expected behavior

Running scripts from the yaml file generates valid VSCode tasks.

### Screenshots

![image](https://user-images.githubusercontent.com/9600796/222386500-3374b6a7-817d-4c92-a54d-ed25906541f4.png)

### Additional context and comments

I post it here, since using Melos with VSCode is mentioned in the website documentation. Lmk if it's the extension issue rather then Melos itself.

**Comment by blaugold** [comment]
@tomwyr Thanks for reporting this issue. It's definitely a bug in the extension. Could you transfer the issue to its [repo](https://github.com/blaugold/melos-code)?

**Comment by tomwyr** [comment]
Thanks @blaugold Moved it to blaugold/melos-code#42.
