### ISSUE TITLE
fix:  typo in error message

### ISSUE THREAD

**Issue by RandalSchwartz** [invertase/melos#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.9.0

### Description

> This workspace has no scripts defined in it's 'melos.yaml' file.

That should be "its" not "it's".

### Steps to reproduce

`melos run` in a project with no scripts.

### Expected behavior

When running... melos should.... not violate the rules of English. :)

### Screenshots

<img width="601" alt="Screen Shot 2023-03-13 at 4 59 59 PM" src="https://user-images.githubusercontent.com/6342/224858006-1c05a7f4-e126-44c6-82b9-dc5b41b42a91.png">

### Additional context and comments

Melos rocks!

**Comment by blaugold** [comment]
@RandalSchwartz Thanks!
