### ISSUE TITLE
request:  Update dependes package cli_utils

### ISSUE THREAD

**Issue by salesandrey** [invertase/melos#499]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Hi, I'm updating the packages in my project and the Melos has conflicts. 

```
melos >=0.4.10-dev.0 depends on cli_util ^0.3.0 and flutter_launcher_icons >=0.13.0 depends on cli_util ^0.4.0,

````

### Reasoning

I think this feature is useful because remove some conflicts with another packages

**Comment by markclemons** [comment]
Have the same issue, would love to get this updated.

**Comment by markclemons** [comment]
I put in a PR to update the dependency https://github.com/invertase/melos/pull/503

**Comment by ondanplatform** [comment]
The same issue occurs.Have you been able to resolve it? @salesandrey @InvertaseBot @markclemons

**Comment by blaugold** [comment]
@ondanplatform You can add a dependency override until a new release of Melos has been published:

```yaml
# In pubspec.yaml

dependency_overrides:
  cli_util: ^0.4.0
```
