### ISSUE TITLE
Melos should fail if a package does not have a "sdk" version constraint

### ISSUE THREAD

**Issue by rrousselGit** [invertase/melos#50]
Consider the following `pubspec.yaml`:

```yaml
name: example
```

Running `pub get` on this yaml file will result in:

```
pubspec.yaml has no lower-bound SDK constraint.                         
You should edit pubspec.yaml to contain an SDK constraint:              
                                                                        
environment:                                                            
  sdk: '>=2.10.0 <3.0.0'                                                
                                                                        
See https://dart.dev/go/sdk-constraint                                  
Running "flutter pub get" in example...                                 
pub get failed (65; See https://dart.dev/go/sdk-constraint)
```

On the other hand, when using `melos boostrap`, it is possible for this error to _not appear_ (possibly when using 2+ packages, including one that has proper SDK constraints).

This can be cause confusion, as it swallows errors.

**Comment by Salakar** [comment]
Agreed, this should be fixed.

**Comment by Salakar** [comment]
This may no longer be required with the pending bootstrap rework (https://github.com/invertase/melos/pull/51) - `melos boostrap` does now surface this up individually and had it do this for me on that very same PR (https://github.com/invertase/melos/pull/51/commits/0f2fd06d622fc3f1192d29edeadeb60138e084da) - though currently it would be down to Flutter to highlight the issue which I believe it currently only does on the `dev` channel.

Thoughts?
