### ISSUE TITLE
fix:   doesn't make the build

### ISSUE THREAD

**Issue by thorito** [invertase/melos#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.0.1

### Description

With version 2.9.0 it had no problem executing 

```
name: myProject

versioning:
  mode: independent

packages:
  - app/*
  - features/**

ide:
  intellij:
    enabled: false

command:
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  build:web:dev:
    run: melos exec --scope=myProject-- "copy_webenv.sh dev && flutter build web -t lib/environments/development/debug/development_main.dart"
    description: Only Windows - Build Web for dev

``` 

but with version 3.0.1 when executing
the same command, doesn't do the build.

### Steps to reproduce

1. melos install
2. melos build:web:dev

### Expected behavior

I would expect it to generate the build

### Screenshots

![screenshot_files](https://user-images.githubusercontent.com/594395/232998027-2f15f614-015e-48bc-a178-7602d5ce7b99.png)

![screenshot_app](https://user-images.githubusercontent.com/594395/232999549-ae614df7-e29d-4135-8cfe-d2f1c5da8d22.png)

### Additional context and comments

Terminal response:

```bash

PS C:\development\flutter\projects\example> melos build:web:dev 
melos run build:web:dev
  └> melos exec --scope=myProject-- "copy_webenv.sh dev && flutter build web -t lib/environments/development/debug/development_main.dart"
     └> RUNNING                                                                                                                      

$ melos exec                                                                                            
  └> copy_webenv.sh dev && flutter build web -t lib/environments/development/debug/development_main.dart
     └> RUNNING (in 0 packages)  <----- (Can't find any package)

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

$ melos exec
  └> copy_webenv.sh dev && flutter build web -t lib/environments/development/debug/development_main.dart
     └> SUCCESS

melos run build:web:dev
  └> melos exec --scope=myProject -- "copy_webenv.sh dev && flutter build web -t lib/environments/development/debug/development_main.dart"
     └> SUCCESS

```

## But if I activate the 2.9.0 if it builds it

**Comment by blaugold** [comment]
In 3.0.0 the semantics of the glob patterns in `packages` changed slightly. You should only use patterns if you want to match multiple packages. `app/*` only finds packages that are themselves in a directory in `app`, such as `app/foo`. To include the package in `app` use the plain `app` path. `./*` would also work, but it's best to avoid glob patterns if not necessary because it reduces startup times.

```yaml
packages:
  - app
  - features/**
```

**Comment by thorito** [comment]
> En 3.0.0, la semántica de los patrones globales `packages`cambió ligeramente. Solo debe usar patrones si desea hacer coincidir varios paquetes. `app/*`solo encuentra paquetes que están en un directorio en `app`, como `app/foo`. Para incluir el paquete en `app`uso, la `app`ruta simple. `./*`también funcionaría, pero es mejor evitar patrones globales si no es necesario porque reduce los tiempos de inicio.
> 
> ```yaml
> packages:
>   - app
>   - features/**
> ```

It has worked with your changes. Thanks !

**Comment by thorito** [comment]
> In 3.0.0 the semantics of the glob patterns in `packages` changed slightly. You should only use patterns if you want to match multiple packages. `app/*` only finds packages that are themselves in a directory in `app`, such as `app/foo`. To include the package in `app` use the plain `app` path. `./*` would also work, but it's best to avoid glob patterns if not necessary because it reduces startup times.
> 
> ```yaml
> packages:
>   - app
>   - features/**
> ```

It has worked with your changes. Thanks !
