### ISSUE TITLE
Request:  Add override to `pupspec_overrrides.yaml` despite local package already being overridden

### ISSUE THREAD

**Issue by simolus3** [invertase/melos#518]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

When adding a dependency override to the main `pubspec.yaml` file for a package that is part of a melos workspace, I would like melos to continue adding its own override to the `pubspec_overrides.yaml` file.

### Reasoning

Maybe I have my publishing setup wrong, but the fixes made in pub for https://github.com/invertase/melos/issues/287 have made it harder for me to publish a set of packages with `dev_dependencies` between them.

In my case, I have a main package `drift` and a code-generating package `drift_dev`. `drift_dev` has a regular dependency on `drift`, and `drift` has a dev-dependency on `drift_dev` for testing purposes. The internal interface between these two packages is less stable than the public API of `drift`, so `drift_dev` depends on a range of minor versions (e.g. `drift_dev` version 2.8.0 would depend on `drift: '>=2.8.0 <2.9.0'`).

My publishing workflow is to first release `drift` and then follow-up with `drift_dev`. Publishing `drift_dev` works fine because the right `drift` version is already on pub.dev. But I can't publish new minor versions of `drift` without workarounds because its dev-dependency on `drift_dev` can't be resolved yet.

Pub stops complaining as soon as I put

```yaml
dependency_overrides:
  drift_dev: any
```

in the pubspec of `drift`, but then melos stops adding the correct path override for `drift_dev` into the generated overrides file. So I have to add that snippet when publishing and remove it afterwards which is unfortunate. If this worked, I could add the main overrides into the primary pubspec for publishing (which is not a problem because `drift_dev` is a dev-dependency) and still rely on melos managing dependencies during development.

**Comment by blaugold** [comment]
The problem is that `dart pub publish` does not take into account `pubspec_overrides.yaml` files. At least it did not before today's releases of the Dart and Flutter SDK. 😄 After upgrading to stable publishing should work. Let me know if that is the case for you.

**Comment by simolus3** [comment]
Ah right, the worst time to post this issue then :D Thanks for the clarification, I guess this is resolved then. If I still have this problem with Dart 3 I can re-open this or file a new issue.
