### ISSUE TITLE
fix: melos.yaml: The name My Awesome Project is not a valid dart package name

### ISSUE THREAD

**Issue by DanielSWolf** [invertase/melos#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.0.1

### Description

According to the [Melos config documentation](https://melos.invertase.dev/~melos-latest/configuration/overview#name), the `name` field in `melos.yaml` is "the name of this project for display purposes within IO environments and IDEs." The docs then offer `name: My Awesome Project` as a valid configuration.

If I do set `name` to "My Awesome Project" and run `melos bootstrap`, I get the following error:

> melos.yaml: The name My Awesome Project is not a valid dart package name

This is surprising to me. For one, I don't understand why a display string needs to be a valid identifier; also, the docs actively suggest that a string containing spaces is a valid value.

### Steps to reproduce

1. Follow the [Getting Started guide](https://melos.invertase.dev/~melos-latest/getting-started), setting `name` in `melos.yaml` to "My Awesome Project" as suggested by the [Melos config documentation](https://melos.invertase.dev/~melos-latest/configuration/overview#name)
2. run `melos bootstrap`

### Expected behavior

I expected the bootstrapping to succeed.

**Comment by blaugold** [comment]
Thanks for opening this issue!

I fixed the docs to give a correct example. I'm not actually sure why exactly the decision was made to require a valid pub package name, so I'll leave it for now.
