### ISSUE TITLE
request: support for bitbucket

### ISSUE THREAD

**Issue by tomasaquiles-ca** [invertase/melos#547]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Add versioning support for bitbucket repositories.

### Reasoning

The feature is missing

**Comment by extrordinaire** [comment]
It would be amazing if you did check this!!!

**Comment by fenrirx22** [comment]
I would happily create PR to add this feature/implementation if it's ok.

**Comment by fenrirx22** [comment]
its ready
https://github.com/invertase/melos/pull/608
