### ISSUE TITLE
fix:  Improve 'getting started' docs

### ISSUE THREAD

**Issue by wujek-srujek** [invertase/melos#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.1.1

### Description

The page https://melos.invertase.dev/~melos-latest/getting-started#bootstrapping mentions what bootstrapping involves, then why it is necessary, and then in 'next steps' it says 'Once successfully bootstrapped ...', but it never tells you how to actually boostrap and never mentions the `melos bootstrap` command. I think it would be helpful to include it in the guide.

### Steps to reproduce

1. Go to https://melos.invertase.dev/~melos-latest/getting-started#bootstrapping.
2. Read it.
3. Wonder how to perform bootstrapping.

### Expected behavior

The page includes the `melos bootstrap` command.

**Comment by spydon** [comment]
It is now mentioned in the first section here:
https://melos.invertase.dev/~melos-latest/getting-started#bootstrapping
