### ISSUE TITLE
fix:  Flutter SDK is not available when use dart pub gloabl activate melos in new system

### ISSUE THREAD

**Issue by jiechic** [invertase/melos#574]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.1.1

### Description

I install fvm and melos in the docker image，setting sdkPath in the melos.yaml ，when i run melos bs on gitlab runner，it's show the log error

```
$ echo y | fvm use && fvm flutter precache
Project now uses Flutter [3.10.6]
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Flutter assets will be downloaded from https://storage.flutter-io.cn/. Make sure you trust this source!
$ melos bootstrap
Resolving dependencies...
Because okmm depends on flutter_test from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.
Flutter users should run `flutter pub get` instead of `dart pub get`.
```

### Steps to reproduce

some setup is on the docker build

1. install dart
```dockerfile
RUN wget --quiet --output-document=dart.deb \
    "https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_3.1.0-1_amd64.deb" && \
    dpkg -i dart.deb && \
    rm --force dart.deb

ENV PATH="$PATH:/usr/lib/dart/bin"
```
2. install melos and fvm
```dockerfile
RUN dart pub global activate fvm && \
    dart pub global activate melos && \
    dart pub global activate junitreport && \
    dart pub global activate full_coverage

ENV PATH="$PATH:/root/.pub-cache/bin"
```
3. precache flutter version
```dockerfile
ENV FLUTTER_VERSION=3.10.6
RUN fvm install $FLUTTER_VERSION && \
    fvm spawn $FLUTTER_VERSION precache
```

the follow setup is on gitlab runner

4. echo y | fvm use && fvm flutter precache
5. melos bootstrap

### Expected behavior

when runner melos will success pub get packages

### Screenshots

![image](https://github.com/invertase/melos/assets/518977/bf62377c-5d80-40d7-9b4e-144a87b86d87)

### Additional context and comments

when i install melos and fvm on local clean system with mac

1. brew install dart
2. dart pub global activate fvm
3. dart pub global activate melos
4. git clone ...project.git
5. cd project
6. fvm use (create link for .fvm/flutter_sdk)
7. melos bs (**error on this setup like the log**)
8. fvm dart pub global run melos (**error on this setup like the log**)
9. fvm flutter pub global run melos (success pub get for all packages)
10. melos bs (now is success for all the next setup with any type run meols)

if i install melos with dart pub global on clean system ,it will be error.
if i run `flutter pub global run melos` or install with `flutter pub global activate melos` then run , i will be success for all time
next，when i deactivate melos and reactivate melos  with `dart pub global activate melos` ,it's success but error on system reboot

**Comment by okki-jk** [comment]
I got the same problem

**Comment by benthillerkus** [comment]
I got the same problem using `puro` instead of `fvm`

**Comment by jiechic** [comment]
because root project use flutter but dart run melos have found it
i change root project to dir app，
then the root project is only dart project 
it fix

**Comment by jiechic** [comment]
it's the same problem #616
