### ISSUE TITLE
request:  support for Azure Devops repo

### ISSUE THREAD

**Issue by computib** [invertase/melos#599]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

It would be nice to add support for Azure Devops git repository (not only GitHub and GitLab).

Related request: #547 

### Reasoning

I'd like to use melos in our company and all our projects are hosted in an on-premise Azure Devops Server...

**Comment by Salakar** [comment]
I'd happily accept PRs that add support for this, I'm not familiar with Azure so can't help there
