### ISSUE TITLE
Pubspecs overwritten with generated pubspecs on windows

### ISSUE THREAD

**Issue by Schwusch** [invertase/melos#60]
I'm unsure whether this behaviour is intended, but the way `melos bootstrap` behaves differs between e.g. Linux and Windows.
On Linux, the pubspecs are seemingly not touched, and on Windows they are overwritten with generated pubspecs.
Those generated pubspecs are not restored with `melos clean` either.

**Comment by Ehesp** [comment]
@Schwusch I don't believe this is intended - what do the modifications look like?

**Comment by Schwusch** [comment]
This is an example from https://github.com/fluttercommunity/plus_plugins:
```
diff --git a/packages/android_intent_plus/pubspec.yaml b/packages/android_intent_plus/pubspec.yaml
index cd67080..ed3860b 100644
--- a/packages/android_intent_plus/pubspec.yaml
+++ b/packages/android_intent_plus/pubspec.yaml
@@ -1,31 +1,27 @@
-name: android_intent_plus
-description: Flutter plugin for launching Android Intents. Not supported on iOS.
-version: 0.5.0-nullsafety.1
-homepage: https://plus.fluttercommunity.dev/
-repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
-
-flutter:
-  plugin:
-    platforms:
-      android:
-        package: dev.fluttercommunity.plus.androidintent
-        pluginClass: AndroidIntentPlugin
-
-dependencies:
-  flutter:
-    sdk: flutter
-
-  platform: ^3.0.0-nullsafety
-  meta: ^1.3.0-nullsafety
-
-dev_dependencies:
-  flutter_test:
-    sdk: flutter
-
-  test: ^1.16.0-nullsafety
-  mockito: ^5.0.0-nullsafety
-  pedantic: ^1.10.0-nullsafety
-
-environment:
-  sdk: ">=2.12.0-133.7.beta <3.0.0"
+# Generated file - do not commit this file.
+description: "Flutter plugin for launching Android Intents. Not supported on iOS."
+homepage: "https://plus.fluttercommunity.dev/"
+name: "android_intent_plus"
+repository: "https://github.com/fluttercommunity/plus_plugins/tree/main/packages/"
+version: "0.5.0-nullsafety.1"
+dependencies:
+  meta: "^1.3.0-nullsafety"
+  platform: "^3.0.0-nullsafety"
+  flutter:
+    sdk: "flutter"
+dependency_overrides:
+dev_dependencies:
+  mockito: "^5.0.0-nullsafety"
+  pedantic: "^1.10.0-nullsafety"
+  test: "^1.16.0-nullsafety"
+  flutter_test:
+    sdk: "flutter"
+environment:
   flutter: ">=1.12.13+hotfix.5 <2.0.0"
+  sdk: ">=2.12.0-133.7.beta <3.0.0"
+flutter:
+  plugin:
+    platforms:
+      android:
+        package: "dev.fluttercommunity.plus.androidintent"
+        pluginClass: "AndroidIntentPlugin"
```

**Comment by Salakar** [comment]
This is definitely not intended, and I'm not exactly sure how this is happening either 😅 the way it works internally is a temporary `.melos_tool` directory is created in the root of your project and your file structure and packages pubspec.yaml files are mirrored into there and those are the ones that are modified and used for pub gets etc. After bootstrap this temp directory is deleted. 

There is no mutation (at least not intentionally) of specs outside this directory.

My Windows machine currently needs a re-install + setting up dev environment again so I can't debug this straight away. Are you able to setup melos for development locally based on: https://github.com/invertase/melos#local-development-setup and see if you can pinpoint the cause?

**Comment by Schwusch** [comment]
> Are you able to setup melos for development ... see if you can pinpoint the cause?

I am rarely using Windows, and I unfortunately haven't got a lot of time in the near future to work on this.
I can tell you that the `.melos_tool` folder is not created, if that is helpful in any way.

I tried doing a patch myself before but, as you will see if you set up a fresh environment, there is a bunch of other bugs that has to be solved first.
For example, adding `dart` in front of `pub get ....` in order to make the commands work without adding SDK internals to the path.

**Comment by Salakar** [comment]
This is fixed in the latest release. Thanks for reporting!

**Comment by Schwusch** [comment]
Nice! Thanks, well done :tada:

**Comment by ahammer** [comment]
I've been dealing with a similar issue on 0.4.11+2

On windows, `flutter packages get` wipes out my lock and reinstall's pub dependencies.
