### ISSUE TITLE
request:  bump SDK version > 3.1.0

### ISSUE THREAD

**Issue by sebastianbuechler** [invertase/melos#605]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

When using the latest version of the `lint` package melos is incompatible:

```
Because my_workspace depends on lint >=2.2.0 which requires SDK version >=3.1.0 <4.0.0, version solving failed.
```

### Reasoning

Keeping dependencies up to date.

**Comment by spydon** [comment]
The `lint` package should preferably be depended on a package level, not in the root pubspec.yaml.
```
packages/
|__ your_package/
   |__ pubspec.yaml <-- in here
pubspec.yaml <-- Only melos version and sdk version
```

**Comment by spydon** [comment]
@sebastianbuechler here is a good example of how the directory structure can look like to not have a package/app in the root:
https://github.com/invertase/melos/issues/616#issuecomment-1856559131

I'll close this meanwhile since Melos doesn't really support having a package or app at the root of the monorepo.

**Comment by sebastianbuechler** [comment]
@spydon I don't have an app in root but specify the workspace there with a melos config file. The issue still persists.

**Comment by spydon** [comment]
> @spydon I don't have an app in root but specify the workspace there with a melos config file. The issue still persists.

Can you post your root pubspec?

**Comment by sebastianbuechler** [comment]
> > @spydon I don't have an app in root but specify the workspace there with a melos config file. The issue still persists.
> 
> Can you post your root pubspec?

Sorry for the late reply. Here it is: 
```
name: company_workspace

environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  melos: ^4.0.0
  lint: ^2.1.2
  ```

**Comment by spydon** [comment]
@sebastianbuechler the `lint` package shouldn't be in there, it should be in the packages pubspec files.
