### ISSUE TITLE
request: support for not specify versions of internal packages

### ISSUE THREAD

**Issue by lohnn** [invertase/melos#609]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

It would be nice if `melos bs` had the option to specify versions of private/internal dependencies as `any` in `pubspec.yaml`.

### Reasoning

We have multiple internal packages in our monorepo for our closed source application, and every time we build a release build all `pubspec.yaml` files are updated with the new dependency versions.

Since this application is, and will continue to be, closed source we don't really care about the version numbers of our internal packages in the dependencies as they are overridden with path dependency anyways, and it only gives us headache when trying to merge PRs and we get conflicts in files we haven't (as developers) even touched ourselves.

### Additional context and comments

We still want the versioning of the packages to exist, as it is a great way for us to keep track of our work, so this feature request is only for the option to change how dependencies are specified.

**Comment by lohnn** [comment]
Also, I can take a stab at implementing this as soon as we have a solution proposal.

**Comment by spydon** [comment]
We're discussing this outside of GitHub, I'll triage this when we've cleared up some things.
