### ISSUE TITLE
request:  Adding repo link to pub.dev

### ISSUE THREAD

**Issue by guyluz11** [invertase/melos#612]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

I think it will be nice to have a link to the repo from pub.dev

Now
![image](https://github.com/invertase/melos/assets/9304740/6af7b6ec-9a30-4611-a72d-555e94f6dcea)

Example from [network_tools](https://pub.dev/packages/network_tools) 
![image](https://github.com/invertase/melos/assets/9304740/d26036d4-fdaf-4cf0-a327-c9fcb2724b31)

### Reasoning

Better use of pub.dev package page options.

**Comment by spydon** [comment]
Now the link is showing, there must have been a hick-up at pub.dev's side.
