### ISSUE TITLE
can melos parse args like bash ,   some_script.sh  $1 $2

### ISSUE THREAD

**Issue by philos3** [invertase/melos#620]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.3.0

### Description

melos run args only work with single  command  in single line scripts

it work fine  in single line and the args is in the end
```
  check-bbj:
    run: cd component/bbj_flutter && git checkout $1
```

However, it fail when the args is in the middle

```
  check-bbj:
    run: cd component/bbj_flutter && git checkout $1  &&  git pull
```
![image](https://github.com/invertase/melos/assets/8424317/17243c43-5d99-4590-bfdd-9eedffc42400)

furthermore , it  also fail when  using a multi-line  

```
  check-bbj:
    run: |
      cd component/bbj_flutter
      git checkout $1
```
![image](https://github.com/invertase/melos/assets/8424317/82e70569-6b80-40cc-93ce-c491350ce36a)

### Steps to reproduce

As mentioned above 

### Expected behavior

can melos parse args like bash ,  we call pase args correct

as :   some_script.sh  $1 $2

**Comment by spydon** [comment]
The multi-line issue is already tracked in #232
