### ISSUE TITLE
fix:  `--no-git-tag-version` does not create a commit

### ISSUE THREAD

**Issue by provokateurin** [invertase/melos#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.4.0

### Description

According to the name and the description `--no-git-tag-version` should only prevent creating git tags and not the commit that is normally generated when using `melos version`.

### Steps to reproduce

1. `melos version --no-git-tag-version`
2. `git log`
3. `git status`

### Expected behavior

There should be a new commit, no git tags and no uncommitted changes.

**Comment by provokateurin** [comment]
Thanks a lot :heart:

**Comment by spydon** [comment]
> Thanks a lot :heart: 

No problem, we'll release this in v4.0.0 later today :)
