### ISSUE TITLE
fix:  Transitive dependencies cannot be overwritten

### ISSUE THREAD

**Issue by JunhuaLin** [invertase/melos#635]
### Is there an existing issue for this?

- [ ] I have searched the existing issues.

### Version

3.4.0

### Description

The package dependencies are as follows: 
a -> b -> c 

project structure：
a
--melos.yaml
--packages
----b
----c

melos.yaml：
packages:
  - packages/c
 
melos.yaml is configured in a to specify c as a local path package by configuring packages and b as a remote dependency. 
Then execute melos bs.

### Steps to reproduce

-

### Expected behavior

-

### Screenshots

-

### Additional context and comments

-

**Comment by spydon** [comment]
You should have all packages listed in `melos.yaml` and also you shouldn't have a package in the root like you do, but inside `packages` or `apps` for example.

**Comment by spydon** [comment]
See https://melos.invertase.dev/getting-started#recommended-directory-structure
