### ISSUE TITLE
Melos on Windows failed to build

### ISSUE THREAD

**Issue by petrnymsa** [invertase/melos#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

4.1.0

### Description

On Windows running any melos command results into error	

```
/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:751:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ```

### Steps to reproduce

```
dart pub global activate melos

>>>
Package melos is currently active at version 4.1.0.
The package melos is already activated at newest available version.
To recompile executables, first run `dart pub global deactivate melos`.
Installed executable melos.
Activated melos 4.1.0.
```

Then 

```
melos --version

>>>

/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:45:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator;
```

<details>
<summary>Details</summary>

Failed to build melos:melos:
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:45:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:49:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:58:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:742:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator => _AvlTreeIterator._(this);
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:746:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator =>
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:751:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:894:38: Error: Type 'BidirectionalIterator' not found.
class _AvlTreeIterator<V> implements BidirectionalIterator<V> {
                                     ^^^^^^^^^^^^^^^^^^^^^
Failed to build melos:melos:
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:45:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:49:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:58:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:742:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator => _AvlTreeIterator._(this);
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:746:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator =>
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:751:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:894:38: Error: Type 'BidirectionalIterator' not found.
class _AvlTreeIterator<V> implements BidirectionalIterator<V> {
                                     ^^^^^^^^^^^^^^^^^^^^^
Failed to build melos:melos:
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:45:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:49:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:58:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:742:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator => _AvlTreeIterator._(this);
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:746:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator =>
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:751:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:894:38: Error: Type 'BidirectionalIterator' not found.
class _AvlTreeIterator<V> implements BidirectionalIterator<V> {
                                     ^^^^^^^^^^^^^^^^^^^^^
Failed to build melos:melos:
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:45:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:49:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:58:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:742:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator => _AvlTreeIterator._(this);
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:746:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator =>
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:751:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/nymsa/AppData/Local/Pub/Cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:894:38: Error: Type 'BidirectionalIterator' not found.
class _AvlTreeIterator<V> implements BidirectionalIterator<V> {
                                     ^^^^^^^^^^^^^^^^^^^^^

</details>

### Expected behavior

Melos command works

### Additional context and comments

I tried:

- Removing all files from .pub-cache
- Reinstalling melos

**Comment by spydon** [comment]
Interesting, which dart version do you have?

**Comment by petrnymsa** [comment]
I have also FVM installed, maybe it is connected with #616 ? However 

```
flutter --version

>>>
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (8 weeks ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
````
and 
```
dart --version
>>>
Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "windows_x64"

➜ (Get-Command dart).Path  
C:\Users\nymsa\fvm\versions\3.16.5\bin\dart.bat
```

**Comment by spydon** [comment]
What does `which melos` say?

**Comment by petrnymsa** [comment]
```
(Get-Command melos).Path
C:\Users\nymsa\AppData\Local\Pub\Cache\bin\melos.bat
```

**Comment by petrnymsa** [comment]
Seems like fixed by running `dart pub cache clean`

**Comment by spydon** [comment]
> Seems like fixed by running `dart pub cache clean`

Good to hear!

**Comment by petrnymsa** [comment]
Reopening. 

First of all, happening on MacOS as well and dart pub cache clean do not work..

```
dart --version
Dart SDK version: 3.2.6 (stable) (Wed Jan 24 13:41:58 2024 +0000) on "macos_arm64"
```
dart pub global activate melos
+ ansi_styles 0.3.2+1s...
+ args 2.4.2
+ async 2.11.0
+ boolean_selector 2.1.1
+ charcode 1.3.1
+ cli_launcher 0.3.1
+ cli_util 0.4.1
+ collection 1.18.0
+ conventional_commit 0.6.0+1
+ file 7.0.0
+ glob 2.1.2
+ graphs 2.3.1
+ http 1.2.0 (1.2.1 available)
+ http_parser 4.0.2
+ io 1.0.4
+ json_annotation 4.8.1
+ matcher 0.12.16+1
+ melos 4.1.0
+ meta 1.12.0
+ mustache_template 2.0.0
+ path 1.9.0
+ platform 3.1.4
+ pool 1.5.1
+ process 5.0.2
+ prompts 2.0.0
+ pub_semver 2.1.4
+ pub_updater 0.4.0
+ pubspec 2.3.0
+ quiver 3.2.1
+ source_span 1.10.0
+ stack_trace 1.11.1
+ stream_channel 2.1.2
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ test_api 0.7.0
+ typed_data 1.3.2
+ uri 1.0.0
+ web 0.4.2 (0.5.0 available)
+ yaml 3.1.2
+ yaml_edit 2.1.1
Building package executables...
Built melos:melos.
Installed executable melos.
Activated melos 4.1.0.
```

Running melos --version

```
melos bs
Building package executable...
Failed to build melos:melos:
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:45:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator;
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:49:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator;
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:58:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:742:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator => _AvlTreeIterator._(this);
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:746:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator =>
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:751:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:894:38: Error: Type 'BidirectionalIterator' not found.
class _AvlTreeIterator<V> implements BidirectionalIterator<V> {
                                     ^^^^^^^^^^^^^^^^^^^^^
Failed to build melos:melos:
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:45:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator;
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:49:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator;
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:58:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:742:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get iterator => _AvlTreeIterator._(this);
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:746:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> get reverseIterator =>
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:751:3: Error: Type 'BidirectionalIterator' not found.
  BidirectionalIterator<V> fromIterator(V anchor,
  ^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/quiver-3.0.1+1/lib/src/collection/treeset.dart:894:38: Error: Type 'BidirectionalIterator' not found.
class _AvlTreeIterator<V> implements BidirectionalIterator<V> {
                                     ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by spydon** [comment]
There must be something strange with your local setup, I just tried on both windows and macos and it works fine. 🤔

Have you tried re-installing flutter?

**Comment by petrnymsa** [comment]
I am using FVM though. No standalone flutter / dart on system

**Comment by spydon** [comment]
> I am using FVM though. No standalone flutter / dart on system

And if you try setting another flutter version through fvm? Maybe your current one is corrupt?

**Comment by spydon** [comment]
Does fvm only have one cache for all installed binaries, no matter which version they were installed with?

**Comment by petrnymsa** [comment]
Reinstalled all fvm installations, cleared fvm list. only flutter 3.16.9 is activated. Still same issue
