### ISSUE TITLE
Melos website is down (except home page)

### ISSUE THREAD

**Issue by vincent-hoodoo** [invertase/melos#647]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

4.1.0

### Description

The website returns a 500 for pages other than the home page

<img width="716" alt="Screenshot 2024-02-19 at 11 43 03" src="https://github.com/invertase/melos/assets/104820536/9daedd9e-3501-410b-9f10-0bd4e23f3f6c">

### Steps to reproduce

Go to https://melos.invertase.dev/~melos-latest/getting-started

### Expected behavior

Website should work

**Comment by mikehardy** [comment]
All of docs.page went down (affected react-native-google-mobile-ads which I help maintain, and a few others)

Appears to be back now.
