### ISSUE TITLE
request:  Update flutter and dart version in all the packages inside monorepo.

### ISSUE THREAD

**Issue by xsahil03x** [invertase/melos#651]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

It would be really beneficial if melos provides a way to easily update the Flutter and Dart version in all the packages available inside monorepo.

### Reasoning

Currently whenever a new Flutter version is released, we have to manually update the version in all of our packages.

**Comment by spydon** [comment]
Hi, this feature already exist, the docs for it are here:
https://melos.invertase.dev/commands/bootstrap#shared-dependencies
