### ISSUE TITLE
Make yes flag work for manual versioning

### ISSUE THREAD

**Issue by chimon2000** [invertase/melos#66]
Currently, there's no way to short circuit the confirmation prompt when setting a version manually.

```bash
melos version some_package --no-changelog --yes 1.0.0
```

It would be nice to have this flag enabled when running in CI.

**Comment by Salakar** [comment]
I will get this added tomorrow hopefully, PRs also welcome, thanks

**Comment by Salakar** [comment]
Now available in version `0.4.6`, thanks
