### ISSUE TITLE
request: log output is the same or similar even if the `-c` option of `melos analyse` is greater than or equal to 1

### ISSUE THREAD

**Issue by koji-1009** [invertase/melos#668]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

melos analyze

### Description

The `melos analyze` command, added from v5, logs differently for `-c 1` and `-c 2`.

`-c 1` case

```bash
$ melos analyze -c 1
Building package executable...
Built melos:melos.
$ melos analyze
  └> dart analyze
     └> RUNNING (in 3 packages)

--------------------------------------------------------------------------------
conventional_commit:
Analyzing conventional_commit...
No issues found!
conventional_commit: SUCCESS
--------------------------------------------------------------------------------
melos:
Analyzing melos...
No issues found!
melos: SUCCESS
--------------------------------------------------------------------------------
melos_workspace:
Analyzing melos...
No issues found!
melos_workspace: SUCCESS
--------------------------------------------------------------------------------

$ melos analyze
  └> dart analyze
     └> SUCCESS
```

`-c 2` case

```bash
$ melos analyze -c 2
Building package executable...
Built melos:melos.
$ melos analyze
  └> dart analyze
     └> RUNNING (in 3 packages)

--------------------------------------------------------------------------------
Analyzing conventional_commit...
Analyzing melos...
No issues found!
No issues found!
Analyzing melos...
No issues found!
--------------------------------------------------------------------------------

$ melos analyze
  └> dart analyze
     └> SUCCESS
```

It would be nice if the two were the same, or at least easier to understand `SUCCESS` per package.

### Reasoning

In environments with many packages (e.g. [plus_plugins](https://github.com/fluttercommunity/plus_plugins)), it is suitable to set many `-c`.
And because it is an environment with many packages, it is nice to have a log output that makes it easy to check the success or failure of each package.

**Comment by jessicatarra** [comment]
It's a logging output issue, the concurrency is actually working fine, but the logs are not being displayed properly to the user, showing the correct information
