### ISSUE TITLE
fix:  melos overrides the applied filter for dependents/dependencies

### ISSUE THREAD

**Issue by xsahil03x** [invertase/melos#675]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

5.2.1

### Description

Currently, the order in which melos exec calculates the packages are as follows:

https://github.com/invertase/melos/blob/main/packages/melos/lib/src/package.dart#L597-L628
1.  `filters` (eg: applyIgnore, applyDirExists, applyFileExists)
2. `applyDiff`
3. `applyIncludeDependentsOrDependencies` if enabled

Because we are executing `applyIncludeDependentsOrDependencies` at the last step, the added packages skips all the filters applied on the first step. So even tho a package is skipped in the first step, it can re-appear through the last `applyIncludeDependentsOrDependencies` step.

### Steps to reproduce

Suppose we have a monorepo with 2 packages.

<table>
<tr>
 <td> Package
 <td> Dependencies
 <td> Have Changes
 <td> Contains Test
<tr>
 <td> Package A
 <td> Package B
 <td> false
 <td> false
<tr>
 <td> Package B
 <td> -
 <td> true
 <td> true
</table>

Now if we try to run the command:

```melos exec --fail-fast --dir-exists="test" --diff=origin/main...HEAD -c 1 --include-dependents -- flutter test```

Ideally the command should only run for `Package B` as `Package A` contains no test. But in the current implementation it will also include `Package A` as it depends on `Package B`.

### Expected behavior

The `filters` should also be applied on `dependents/dependencies`.

**Comment by spydon** [comment]
```
    --include-dependents                         Include all transitive dependents for each package that matches the other filters. The included packages skip --ignore and --diff checks.
```

This is how it is intended to work, and also how the docs describe it.

**Comment by xsahil03x** [comment]
> ```
> --include-dependents    Include all transitive dependents for each package that matches the other filters. The included packages skip --ignore and --diff checks.
> ```
> 
> This is not a bug, it is how it is intended to work, and also how the docs describe it.

Thanks, i missed.

**Comment by Pavel-Sulimau** [comment]
Hey @xsahil03x, I ended up implementing the approach of setting the global `MELOS_PACKAGES` filter with the values from `melos list --diff=origin/main...HEAD --include-dependents` in the CI pipeline for our big project. 

The approach is described in https://itnext.io/flutter-selective-ci-checks-2d79ffbd26e5 article. Hopefully, it may be a workaround for you as well!
