### ISSUE TITLE
request: Support `--set-exit-if-changed` in `melos format`

### ISSUE THREAD

**Issue by spydon** [invertase/melos#685]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

melos format --set-exit-if-changed

### Description

The `--set-exit-if-changed` flag from `dart format` would be good to propagate from `melos format`

### Reasoning

When running `melos format` in CI you usually want to do a check with `--set-exit-if-changed`.

**Comment by utamori** [comment]
This appears to have already been added

**Comment by spydon** [comment]
Good catch, was solved by https://github.com/invertase/melos/pull/709
