### ISSUE TITLE
Feature request: Configurable commit messages

### ISSUE THREAD

**Issue by shyndman** [invertase/melos#69]
Hello there,

This would be a helpful feature for me. Are you open to contributions?

I would likely approach this similarly to Lerna's approach — a configurable `message` field somewhere in melos.yaml, probably associated with the command.

Thanks!

**Comment by Salakar** [comment]
> Are you open to contributions?

Yes, definitely. I left a todo in place for this very thing here: https://github.com/invertase/melos/blob/master/packages/melos/lib/src/command/version.dart#L532-L536

**Comment by shyndman** [comment]
Cool! I'll take a stab at it. :)

**Comment by shyndman** [comment]
Hey @Salakar, can we get this deployed?

**Comment by Salakar** [comment]
On it right now

**Comment by shyndman** [comment]
Thank you :)

**Comment by Salakar** [comment]
Done

**Comment by shyndman** [comment]
Thanks dude.
