### ISSUE TITLE
[bug] running melos publish in github actions throws

### ISSUE THREAD

**Issue by iapicca** [invertase/melos#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

^5.3.0

### Description

running melos publish in github actions throws

```console
Run yes | melos publish --no-dry-run --git-tag-version
melos publish
  └> /home/runner/work/yak_packages/yak_packages

Reading pub registry for package information...

The following packages WILL be published to the registry:

Package Name    Registry    Local
yak_result      2.1.0       3.0.0
yak_runner      2.1.0       3.0.0
yak_test        2.1.0       3.0.0
yak_flutter     2.1.0       3.0.0
CancelledException: Operation was canceled.
yes: standard output: Broken pipe
Error: Process completed with exit code 1.
```

see [full job results](https://github.com/yakforward-ou/yak_packages/actions/runs/8736090806)
I got a similar error in the past
- https://github.com/invertase/melos/issues/380
but `yes | melos publish --no-dry-run --git-tag-version` doesn't help

### Steps to reproduce

you can see the code [here](https://github.com/yakforward-ou/yak_packages/tree/fix_issues_240)

### Expected behavior

publishing from github actions  used to work

**Comment by spydon** [comment]
It is not possible to do publishing from GitHub until [this issue](https://github.com/dart-lang/pub-dev/issues/7177#issuecomment-1827201944) is solved, you can put a thumbs up on it to show that it's a feature that you would like.

**Comment by iapicca** [comment]
> It is not possible to do publishing from GitHub until [this issue](https://github.com/dart-lang/pub-dev/issues/7177#issuecomment-1827201944) is solved, you can put a thumbs up on it to show that it's a feature that you would like.

done
unless keeping this issue open is of any use for you to track the problem
feel free to close it

**Comment by spydon** [comment]
This feature will btw be available through the [melos-action](https://github.com/marketplace/actions/melos-action) once it is released, so you won't have to build it yourself. :)
