### ISSUE TITLE
Consider adding `topics` to `pubspec.yaml` for better discoverability

### ISSUE THREAD

**Issue by jonasfj** [invertase/melos#713]
I'd suggest adding the following lines to `pubspec.yaml`:

```yaml
topics:
  - tool
  - repository-management
```

This is inspired by [`mono_repo`](https://pub.dev/packages/mono_repo) which is a similar tool, though probably less polished.

Topics helps users on pub.dev discover packages, and related packages :D

Originally, filed a PR: https://github.com/invertase/melos/pull/712, but I can't sign the CLA without a CLA-review, so it's probably easier for someone else to decide what topics `melos` should have and add them to `pubspec.yaml`.

----

See also: https://dart.dev/tools/pub/pubspec#topics

**Comment by spydon** [comment]
Super, I'll add it once I'm back in Sweden!
(I'll do the same for Flame too)
