### ISSUE TITLE
request: license checker

### ISSUE THREAD

**Issue by MarkOSullivan94** [invertase/melos#722]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

melos licenses

### Description

As a developer, I would like Melos to alert me to any licenses found by packages which I have used in my project which do not permit commercial use

### Reasoning

This feature would be very useful incorporated into CI workflows and will help avoid companies from getting caught out by a package moving away from a commercial friendly license in a new version

### Additional context and comments

This was idea inspired by the great work by the [Very Good Ventures](https://verygood.ventures/)[^1] team and I felt that Melos could benefit from something similar

[^1]: You can find the [very_good_cli](https://github.com/VeryGoodOpenSource/very_good_cli/)'s implementation [here](https://github.com/VeryGoodOpenSource/very_good_cli/blob/main/lib/src/commands/packages/commands/check/commands/licenses.dart)

**Comment by spydon** [comment]
I think this is too specific for being built-in in Melos, but it would be easy to use the VGV cli from a Melos script if you need it in your projects. :)
