### ISSUE TITLE
request:  Can we have a option to show latest tag of each packages.

### ISSUE THREAD

**Issue by ebsangam** [invertase/melos#736]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

If melos provide a way to output latest tag (versions) of packages in readme it would be great. 

### Reasoning

So when maintaining private repo it would be easy to developer to see the latest available packages versions.

**Comment by spydon** [comment]
It sounds strange that it should print it in the readme, but sounds useful to have a verbose output for `melos list` where it prints the versions.

**Comment by Salakar** [comment]
> to output latest tag (versions) of packages in readme it would be great.

We do have this already via '-l' on `melos list`, 
<img width="1415" alt="image" src="https://github.com/user-attachments/assets/c54445a9-8fc5-4261-8a61-467ee908f3b5">

**Comment by spydon** [comment]
> We do have this already via '-l' on `melos list`, 

That's great! Didn't know about that flag. 
I think we can close this one then, because the part about adding the version to the readme is not something we want I think.
