### ISSUE TITLE
fix: `melos --version` shows wrong value

### ISSUE THREAD

**Issue by feinstein** [invertase/melos#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

6.1.0 or 3.2.0

### Description

When I run `melos --version` it shows:

```console
3.2.0
There is a new version of melos available (6.1.0).
```

Then I try `dart pub global deactivate melos` and `dart pub global activate melos` and I get this:

```console
....
+ typed_data 1.3.2
+ uri 1.0.0
+ web 1.0.0
+ yaml 3.1.2
+ yaml_edit 2.2.1
Building package executables...
Built melos:melos.
Installed executable melos.
Activated melos 6.1.0.
```

And then again if I run `melos --version` I get:

```console
3.2.0
There is a new version of melos available (6.1.0).
```

### Steps to reproduce

1. `melos --version`
1.`dart pub global deactivate melos`
1.`dart pub global activate melos`
1. `melos --version`

### Expected behavior

`melos --version` should show 6.1.0

### Additional context and comments

Dart SDK version: 3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on "macos_arm64"

**Comment by spydon** [comment]
You have specified the version that it is showing in your root pubspec, so this is not a bug.

**Comment by feinstein** [comment]
What do you mean by the version in my root pubspec.yaml? How can I know the version of the melos tool that I have installed in my system?

**Comment by spydon** [comment]
> What do you mean by the version in my root pubspec.yaml? How can I know the version of the melos tool that I have installed in my system? 

Run `melos --version` outside of a monorepo and you'll know the global version that is installed.
Check your `pubspec.yaml` file in the root of the monorepo you currently are in and you'll see that it's an older version specified there.

**Comment by feinstein** [comment]
Oh I see, is this documented? Because when I run `melos --help` I only see the description of `version` for generating new versions of packages

**Comment by spydon** [comment]
It could probably be better documented indeed, both on the site and in the cli. Would you like to contribute with a PR with updated docs? :)

**Comment by feinstein** [comment]
I don't mind, but I don't know what is the expected behaviour, so I could document it

**Comment by spydon** [comment]
The expected behavior is the one that you have observed, `--version` reports the version of Melos that it is currently using, so if it is in a repo that constraints it to a lower version than what is installed globally that is the version that will be reported, and if you're not in a repo, or a repository that doesn't constrain the version, it will report the version installed globally.
