### ISSUE TITLE
Request: Add --include-dependents filtering option

### ISSUE THREAD

**Issue by shyndman** [invertase/melos#74]
`--depends-on` is great, but what I'm finding in practice is that I often have to write the `melos exec` twice to do what I need.

For example, if I want to test all packages that might be affected by a change to `some_package`.

1. `melos exec --scope=some_package {testing_command}`
2. `melos exec --depends-on=some_package {testing_command}`

An `--include-dependents` option would mean that I could combine this into a single command.

**Comment by Salakar** [comment]
So would this be used like this: `melos exec --scope=some_package --include-dependents {testing_command}`?

**Comment by shyndman** [comment]
Yup. Exactly that.

**Comment by Salakar** [comment]
SGTM

**Comment by shyndman** [comment]
Closed via #83
