### ISSUE TITLE
request:  Add kebab case

### ISSUE THREAD

**Issue by feinstein** [invertase/melos#742]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

I need to set firebase project names in kebab case, but trying to use `{{name.kebabCase()}}` doesn't work.

**Comment by spydon** [comment]
Can you explain more what it is that you're trying to do?

**Comment by feinstein** [comment]
Moustache allows us to use some case modifyers. `snakeCase()` works, but `kebabCase()` doesn't.

I have project titles like "My Project" and I need to generate a package id like "my_project" and a firebase project id like "my-project". It's a lot easier if I can use only 1 variable for these and just apply different cases using `{{projectName.snakeCase()}}`.

**Comment by spydon** [comment]
This is an issue for the moustache_template package, and not for Melos.
