### ISSUE TITLE
docs: Update docs concurrency description

### ISSUE THREAD

**Issue by jihuncha** [invertase/melos#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

6.1.0

### Description

I was looking into the issue and noticed that the default value for concurrency was changed to Platform.numberOfProcessors in [this pull request](https://github.com/invertase/melos/pull/654). However, the documentation still states that the default is 5 (https://melos.invertase.dev/configuration/scripts#concurrency). is it ok not to update docs?

### Steps to reproduce

.

### Expected behavior

Please change docs description.

**Comment by spydon** [comment]
Thanks for notifying us, it will be fixed once #744 is merged
