### ISSUE TITLE
request:  Dockerfile example 

### ISSUE THREAD

**Issue by flutter-painter** [invertase/melos#748]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Please show me how to build a Dockerfile while using melos, e.g.

- my_project
  - packages
  - server
  
Documentation here is scarce and not working

https://hub.docker.com/_/dart

### Reasoning

I think this feature will be useful because we all need to deploy our apps at some point...

**Comment by spydon** [comment]
You just run `dart pub global activate melos` if you're using a docker file with Dart (just like you would on your normal computer), and then add the bin path to your `PATH` as described in the `activate` process.

**Comment by spydon** [comment]
This is not a melos issue, but I'll try to help you.
What errors are you getting?

**Comment by spydon** [comment]
Which line fails with what? Does the first `pub get` pass?

**Comment by flutter-painter** [comment]
pub get pass
What fails is : 
RUN dart compile exe apps/server/bin/server.dart -o bin/server

**Comment by spydon** [comment]
Can you post the output of `dart info`?

**Comment by spydon** [comment]
Ah, I see the problem. You haven't run `pub get` for your actual application, only for the root pubspec.
You have to cd into the correct diretory first, or if you're using melos run `melos bootstrap` first.

**Comment by flutter-painter** [comment]
Yes this is Docker's problem.
The app runs fine and melos bootstrap works fine as well.
I understand that the Dockerfile need to be at the root to access packages.
But building from the Dockerfile fails when I run :  `docker build -t server .`

I am confused, does it work out of the box for other melos users doing building docker ?
The repo is public if you want to test it : https://github.com/weebi-com/server

Below is dart info / project info

- sdk constraint: '>=3.1.5 <4.0.0'
- dependencies:
- dev_dependencies: melos

**Comment by spydon** [comment]
You're never running `melos bootstrap` or `pub get` in your apps directory in the dockerfile.
