### ISSUE TITLE
Should --depends-on include transitive dependents?

### ISSUE THREAD

**Issue by shyndman** [invertase/melos#75]
I'm noticing that only Melos only considers direct dependents with the `--depends-on` option, but it seems to me that the entire set of transitive dependents might be more useful (since it represents any package possibly impacted by a change).

Should `--depends-on` be changed to includes transitives? 
Alternatively, if we wanted to avoid a breaking change, should a new option be added? `--depends-on-transitive`?

**Comment by Salakar** [comment]
`--depends-on-transitive` makes sense to me to avoid breaking changes, I also viewed `--depends-on` as useful for direct dependencies

**Comment by shyndman** [comment]
Testing or analysis are both good uses.

Let's say `c` depends on `b` depends on `a`.

`b` has an API that returns an instance of a class defined in `a`. `c` calls `b`'s API.

Now someone goes and changes the shape of `a`'s class in some breaking way. `b` may never actually interact with the class' members, so analysis will succeed there, but `c` does...and now we're broken.

And keep in mind, `c` does not require a direct dependency on `a` to interact with that object. Technically, `c` can even import `a` just because it depends on `b` (which is bad form, but possible).

It's also pretty handy to see the entire set (or even tree...) of dependents. Right now, if I wanted that, I would have to `melos list --all --graph`, parse the object, and walk it. Doable, but it's work.

**Comment by Salakar** [comment]
That makes sense, just wanted to know more about the use case. This sounds good to me as a feature. 👍

**Comment by shyndman** [comment]
Cool

**Comment by shyndman** [comment]
`--include-dependents` and `--include-dependencies` both include transitives, so my needs are met. Unless you want this, I'm going to close it off.
