### ISSUE TITLE
Request: Introduce a "commands" section to the workspace config

### ISSUE THREAD

**Issue by shyndman** [invertase/melos#76]
In order to persist command configuration, is there any interest in including a commands section to `melos.yaml`, similarly to `lerna.json`?

**Comment by Salakar** [comment]
Yes! This was something I wanted to do as well, just haven't got around to it yet

**Comment by shyndman** [comment]
I'm going to build this out quickly and pop a messages default in there.

**Comment by Salakar** [comment]
> I'm going to build this out quickly and pop a messages default in there.

A good place as any to start from :)
