### ISSUE TITLE
fix:  Broken doc link https://invertase.docs.page/melos/~melos-latest/getting-started

### ISSUE THREAD

**Issue by josephmangmang** [invertase/melos#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

latest

### Description

Link not found when clicking link inside doc
https://invertase.docs.page/melos~melos-latest

### Steps to reproduce

1. go to https://invertase.docs.page/melos~melos-latest
2. click tab link or any link
3. it will show not found

### Expected behavior

Page should load correctly

### Screenshots

![Screenshot 2024-10-04 at 12 34 55 PM](https://github.com/user-attachments/assets/76513c5f-8b58-4cf7-8fdc-694eedc4d746)

**Comment by Ehesp** [comment]
This is an issue on docs.page end - taking a look

**Comment by Ehesp** [comment]
Fixed!
