### ISSUE TITLE
fix: Vercel "Failed to verify your browser" error visiting docs https://melos.invertase.dev/getting-started

### ISSUE THREAD

**Issue by tgrushka** [invertase/melos#775]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

N/A

### Description

Constant "We're verifying your browser" messages trying to visit melos documentation, followed by "Failed to verify your browser" -- by Vercel Security Checkpoint (Cloudflare?).

Firefox 131.0.2 (aarch64).

Had no issue earlier today.

This is (likely) a static documentation site. There should never be a gateway into it. S3, etc. would handle it just fine.

I'm trying to (re-learn) melos, this is really annoying. Probably not y'all's fault, but these "tech bro" gatekeeper companies taking over all of our web experiences (aka, Vercel, Cloudflare, et. al.) are really getting annoying. Someone in D.C. should do something.

### Steps to reproduce

1. Visit https://melos.invertase.dev/getting-started at a time when Vercel / (probably) Cloudflare has a high traffic load and just decides to reject regular users rather than pass them through.
2. Get error.

### Expected behavior

I expect a (likely static) documentation site to just load.

### Screenshots

<img width="847" alt="image" src="https://github.com/user-attachments/assets/ae77ec08-c1a3-4e28-a714-1bc3ddb90544">

### Additional context and comments

Please dump Vercel if possible. They don't need your money if this is the experience they want to deliver.

**Comment by spydon** [comment]
Does this still happen? It was probably a temporary glitch.

**Comment by spydon** [comment]
Closing since it seems to work properly from all browsers and locations I've tried.

**Comment by Ehesp** [comment]
There was a big DDOS attack on Friday which hit Cloudflare & Vercel (https://twitter.com/rauchg/status/1845787993174397248), so they increased checks hence why you saw this.
