### ISSUE TITLE
request:  Is it possible for 'melos run' to know the current working directory?

### ISSUE THREAD

**Issue by haodong404** [invertase/melos#776]
### Is there an existing feature request for this?

- [ ] I have searched the existing issues.

### Description

There is a script:
```yaml
scripts:
  pwd:
    run: pwd
```
When I run `melos pwd`, it will print the project's root path, even if I execute it in a package directory. But it is perfect if melos can aware the working directory.

### Reasoning

It's helpfull for executing dart scripts or other complex commands.

**Comment by spydon** [comment]
You can run it with `exec` and `scope` it to the package you want to run it in. `run` will always be in the root, that's by design.
