### ISSUE TITLE
fix:  bootstrap fails when version is not specified

### ISSUE THREAD

**Issue by MohiuddinM** [invertase/melos#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

6.2.0

### Description

```
type 'Null' is not a subtype of type 'String'

#0      new ExternalHostedReference.fromJson (package:pubspec/src/dependency.dart:138:37)
#1      new DependencyReference.fromJson (package:pubspec/src/dependency.dart:25:42)
#2      new PubSpec.fromJson.<anonymous closure> (package:pubspec/src/pubspec.dart:107:68)
#3      JsonParser.mapValues.<anonymous closure> (package:pubspec/src/json_utils.dart:113:45)
#4      MapBase.forEach (dart:collection/maps.dart:35:13)
#5      JsonParser.mapValues (package:pubspec/src/json_utils.dart:112:7)
#6      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:107:15)
#7      PubSpec.loadFile (package:pubspec/src/pubspec.dart:128:15)

```

### Steps to reproduce

1. Add a hosted dependency with no version specified
2. run: melos bootstrap

### Expected behavior

bootstrap should succeed

**Comment by spydon** [comment]
Curious, I just tried and it works fine for me.
Can you share a full reproduction?

**Comment by MohiuddinM** [comment]
> Curious, I just tried and it works fine for me. Can you share a full reproduction?

There is no way this works, because this is the json being passed:
`{hosted: https://dart.pkg.jetbrains.space/xyz/p/main/pub/}`

And ofc this is gonna throw a null error because there is no null check before calling:
`VersionConstraint.parse(json['version']),`

**Comment by MohiuddinM** [comment]
Probably we need to change this line to:
`json['version'] is String ? VersionConstraint.parse(json['version']) : null,`

**Comment by spydon** [comment]
Aah, I missed the fact that you are talking about `hosted` dependencies.

> Probably we need to change this line to:
json['version'] is String ? VersionConstraint.parse(json['version']) : null,

Sounds good, do you want to provide a PR?

**Comment by MohiuddinM** [comment]
But this change is in the pubspec package, not in melos. And that package is discontniued.

**Comment by spydon** [comment]
Ah of course, I though we already had an issue for migrating away from that package, but I couldn't find one so I opened https://github.com/invertase/melos/issues/778

**Comment by spydon** [comment]
This should be solved by https://github.com/invertase/melos/pull/794
