### ISSUE TITLE
request:  Supports to multiple commands line by line in run field.

### ISSUE THREAD

**Issue by nespjin** [invertase/melos#790]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Now we need to add && to run multiple commands, such as:
```yaml
run: |
  rm file1.txt && rm file2.txt
```

or

```yaml
run: |
  rm file1.txt \
  && rm file2.txt
```

It's handy if we can write multiple commands line by line, for example:
```yaml
run: |
  rm file1.txt
  rm file2.txt
```

### Reasoning

This improvement will make it easier to write multiple commands

**Comment by spydon** [comment]
We already have this, it's called `steps`. :)
https://melos.invertase.dev/configuration/scripts#steps
