### ISSUE TITLE
fix:  `melos analyze` is running `dart analyze` for Flutter packages

### ISSUE THREAD

**Issue by mahmuttaskiran** [invertase/melos#792]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

6.1.0

### Description

When I run melos analyze, it fetches dependencies for the root project, allowing the analysis to succeed for the root. However, for the packages, it fails because it does not resolve dependencies before running the analysis for each package.

### Steps to reproduce

- Run flutter clean for each package to delete the pubspec.lock files: melos exec --flutter clean.
- Run melos analyze.

### Expected behavior

It should resolve the packages for each package if needed. Like `flutter analyze` do.

**Comment by mahmuttaskiran** [comment]
One more info: It's running `dart analyze` even for flutter workspaces, and that's why it's not resolving dependencies

**Comment by spydon** [comment]
You're always supposed to have run `bootstrap` (which runs `pub get`) before you run any Melos commands.

**Comment by mahmuttaskiran** [comment]
But that's not the case with the flutter analyze command. It resolves dependencies (runs pub get) before analyzing, if needed. We've delivered a fix for this.
https://github.com/invertase/melos/pull/793
