### ISSUE TITLE
fix:  Melos update to intl 0.20.0

### ISSUE THREAD

**Issue by lore-co** [invertase/melos#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

6.2.0

### Description

As title says, a new Intl version is out and Melos should be upgraded

So, because depurart depends on both intl ^0.20.0 and melos ^6.2.0, version solving failed

### Steps to reproduce

Flutter pub get with melos 6.2.0 and into 0.20.0

### Expected behavior

Melos should be updated

**Comment by spydon** [comment]
You are having one of your packages in the root of your monorepo, that is not recommended, since your normal dependencies shouldn't be constrained by melos dependencies. I suggest that you move in your root package to either `packages/` or `apps/`.
