### ISSUE TITLE
Support custom flutter sdk / dart sdk paths

### ISSUE THREAD

**Issue by passsy** [invertase/melos#81]
I'm using [`flutter_wrapper`](https://github.com/passsy/flutter_wrapper) in my projects and it's not possible to pass in a custom flutter sdk path. This causes `bootstrap` to fail because my project isn't compatible with the flutter version in `$PATH`.

This request is similar to #21 but more general as @orestesgaolin wrote https://github.com/invertase/melos/issues/21#issuecomment-745978584

> Another idea is to allow to pass arbitrary path to Flutter installation. This way it wouldn't be tied to fvm only. 

### Suggestion

```bash
melos bootstrap --flutter-sdk=.flutter
```

**Comment by Salakar** [comment]
I think we could support this but I'm not a fan of adding a new parameter for it, could we add an `env` variable for it instead?

```sh
FLUTTER_SDK=.flutter
melos bootstrap
```

**Comment by mikehardy** [comment]
As a tool user in CI environments I like it better when everything is a command line or an env var personally. Normally I have a preference for command line parameters, as configuring a tool in scripts using both styles (env var and command line parameters) feels cumbersome for me. Same command length in the end, but now two styles? :thinking:

**Comment by passsy** [comment]
I'm more in favor of the parameter. I have multiple Flutter SDKs on my local machine, all projects use a different one. Setting an environment variable isn't practical in that case.

But I can see it being useful on CI.

![why not both](https://media.giphy.com/media/3ohfFhG5VDtDTzQv2o/giphy.gif)

**Comment by Salakar** [comment]
We can do both I guess!

Wouldn't setting `--flutter-sdk=.flutter` on every command with pub not be tedious, is there any suggestions on how we can improve this? If `.flutter` inside the project is a fairly standard thing for fvm (? not familiar with it) then we could also just detect that and use that for the sdk, maybe

**Comment by shyndman** [comment]
This could also be an opportunity for using melos.yaml

**Comment by passsy** [comment]
> Wouldn't setting `--flutter-sdk=.flutter` on every command with pub not be tedious?

melos could check for some default locations, similar to vscode https://github.com/Dart-Code/Dart-Code/blob/3af8a9c119a7adc4b4a59df4c630d149ed136e11/src/extension/sdk/utils.ts#L246-L260. `--flutter-sdk` shouldn't be the end solution but an intermediate to get things going.

**Comment by acoutts** [comment]
@passsy we are doing final checks of the PR here which implements support for a custom sdk - would appreciate if you had any feedback.

* You can specify `sdkPath` in your `melos.yaml`
* You can specify `--sdk-path ..` when passing melos commands
* You can set the `MELOS_SDK_PATH` environment variable when you want a custom sdk path setting to cascade down dart commands (such as when doing `melos [custom command name]`

**Comment by passsy** [comment]
Looks perfect 👍
