### ISSUE TITLE
Request: Support a prepublish lifecycle method

### ISSUE THREAD

**Issue by shyndman** [invertase/melos#88]
I'd like to be able to run a script before publishing. If that script fails, publishing should not continue.

The use case I have in mind is running tests, running pana, etc.

**Comment by Salakar** [comment]
Version already supports this for `version` and `postversion` so shouldn't be hard to mirror this into the publish command.


https://github.com/invertase/melos/blob/master/packages/melos/lib/src/command/version.dart#L522-L525

https://github.com/invertase/melos/blob/master/packages/melos/lib/src/command/version.dart#L589-L593
